// app/command-center/retail/page.tsx
import Link from 'next/link';
import { Store, ArrowRight, ShoppingBag, CreditCard, Users } from 'lucide-react';

export default function RetailManagementPage() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة مع زر العودة */}
                  <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div className="flex items-center gap-4">
                                    <Link href="/command-center" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                <ArrowRight className="w-5 h-5 text-slate-700" />
                                                          </Link>
                                                                    <div>
                                                                                <h1 className="text-2xl font-bold text-slate-800">إدارة محلات التجزئة</h1>
                                                                                            <p className="text-slate-500 text-sm mt-1">متابعة طلبيات المحلات، الأرصدة، وإدارة حسابات التجار والديون</p>
                                                                                                      </div>
                                                                                                              </div>
                                                                                                                      <div className="flex gap-3">
                                                                                                                                <Link href="/command-center/retail/credit" className="bg-amber-600 hover:bg-amber-700 text-white px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 transition-colors">
                                                                                                                                            <CreditCard className="w-4 h-4" />
                                                                                                                                                        إدارة الآجل والديون
                                                                                                                                                                  </Link>
                                                                                                                                                                          </div>
                                                                                                                                                                                </div>

                                                                                                                                                                                      {/* إحصائيات سريعة لقسم التجزئة */}
                                                                                                                                                                                            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">المحلات النشطة</span>
                                                                                                                                                                                                                                      <Store className="w-5 h-5 text-amber-600" />
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">186 محل</h3>
                                                                                                                                                                                                                                                                    <span className="text-emerald-600 text-xs mt-1 block">متصلون عبر المنصة حالياً</span>
                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">طلبات اليوم</span>
                                                                                                                                                                                                                                                                                                                      <ShoppingBag className="w-5 h-5 text-blue-600" />
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">45 طلبية</h3>
                                                                                                                                                                                                                                                                                                                                                    <span className="text-slate-400 text-xs mt-1 block">قيد التجهيز والتوصيل</span>
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">إجمالي الأرصدة المعلقة</span>
                                                                                                                                                                                                                                                                                                                                                                                                      <CreditCard className="w-5 h-5 text-purple-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">12,450,000 د.ع</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-slate-400 text-xs mt-1 block">ضمن حدود التمويل المسموح</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* جدول عرض المحلات (قيد الربط مع Supabase) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="font-bold text-slate-800 text-lg">أحدث محلات التجزئة المسجلة</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full">جاهز للربط بالقاعدة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="p-8 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    سيتم جلب تفاصيل المحلات وحالة الطلبات تلقائياً من جداول قاعدة بيانات Supabase...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        update