'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { DollarSign, ArrowRight, Wallet, TrendingUp, CreditCard, ArrowUpRight, ArrowDownLeft, AlertCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';

export default function FinancialsDashboard() {
  const router = useRouter();
    const [transactions, setTransactions] = useState<any[]>([]);
      const [loading, setLoading] = useState(false);
        const [error, setError] = useState('');

          useEffect(() => {
              fetchFinancialData();
                }, []);

                  const fetchFinancialData = async () => {
                      try {
                            setLoading(true);
                                  const { data, error: err } = await supabase.from('orders').select('*');
                                        if (err) throw err;
                                              if (data) setTransactions(data);
                                                  } catch (err: any) {
                                                        setError('فشل في استرجاع السجلات المالية.');
                                                            } finally {
                                                                  setLoading(false);
                                                                      }
                                                                        };

                                                                          const totalRevenue = transactions.reduce((acc, curr) => acc + (curr.total_amount || 0), 0);

                                                                            return (
                                                                                <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic" dir="rtl">
                                                                                      {/* الشريط العلوي */}
                                                                                            <header className="bg-slate-900/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
                                                                                                    <div className="flex items-center gap-3">
                                                                                                              <button
                                                                                                                          onClick={() => router.back()}
                                                                                                                                      className="h-10 w-10 rounded-xl bg-slate-800 text-slate-300 hover:text-white grid place-items-center transition"
                                                                                                                                                >
                                                                                                                                                            <ArrowRight size={20} />
                                                                                                                                                                      </button>
                                                                                                                                                                                <div>
                                                                                                                                                                                            <h1 className="text-sm font-black text-white">المركز المالي والتقارير النقدية</h1>
                                                                                                                                                                                                        <p className="text-[11px] text-slate-400">متابعة الأرباح، الإيرادات، والتدفقات بالدينار العراقي</p>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                      {/* المحتوى الرئيسي */}
                                                                                                                                                                                                                                            <main className="max-w-6xl mx-auto p-6 space-y-6">
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            {/* بطاقات الملخص المالي */}
                                                                                                                                                                                                                                                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                              <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                          <div className="h-12 w-12 rounded-2xl bg-emerald-500/10 text-emerald-400 grid place-items-center border border-emerald-500/20">
                                                                                                                                                                                                                                                                                                        <Wallet size={22} />
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                              <p className="text-xs text-slate-400">إجمالي الإيرادات</p>
                                                                                                                                                                                                                                                                                                                                                            <p className="text-lg font-black text-emerald-400 mt-0.5">{totalRevenue.toLocaleString()} د.ع</p>
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="h-12 w-12 rounded-2xl bg-blue-500/10 text-blue-400 grid place-items-center border border-blue-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                                      <TrendingUp size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs text-slate-400">صافي الأرباح التقديرية</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-lg font-black text-white mt-0.5">{(totalRevenue * 0.15).toLocaleString()} د.ع</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="h-12 w-12 rounded-2xl bg-amber-500/10 text-amber-400 grid place-items-center border border-amber-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CreditCard size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs text-slate-400">الذمم والديون المعلقة</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-lg font-black text-amber-400 mt-0.5">0 د.ع</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* سجل العمليات المالية */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-sm font-bold text-white flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <DollarSign size={18} className="text-emerald-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        سجل الحركات النقدية الحديثة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-rose-500/10 border border-rose-500/30 text-rose-400 p-3 rounded-xl text-xs flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AlertCircle size={16} className="shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>{error}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-center py-20 text-slate-500 text-xs">جاري تحميل السجلات المالية...</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : transactions.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-center py-20 text-slate-500 text-xs">لا توجد حركات مالية مسجلة حالياً.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {transactions.map((tx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={tx.id} className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="h-10 w-10 rounded-xl bg-emerald-500/10 text-emerald-400 grid place-items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ArrowDownLeft size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs font-bold text-white">تحصيل مالي - طلب #{tx.id.slice(0, 8)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-[10px] text-slate-400 mt-0.5">الحالة: {tx.status || 'مكتمل'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs font-black text-emerald-400">+{tx.total_amount || 0} د.ع</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
