// app/command-center/administration/finance/page.tsx
import Link from 'next/link';
import { DollarSign, ArrowRight, ShieldCheck, TrendingUp, Wallet } from 'lucide-react';

export default function AdministrationFinancePage() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة مع زر العودة */}
                  <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div className="flex items-center gap-4">
                                    <Link href="/command-center/administration" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                <ArrowRight className="w-5 h-5 text-slate-700" />
                                                          </Link>
                                                                    <div>
                                                                                <h1 className="text-2xl font-bold text-slate-800">إدارة الخزينة والعملات</h1>
                                                                                            <p className="text-slate-500 text-sm mt-1">ضبط أسعار الصرف، متابعة السيولة النقدية، وتسوية المعاملات المالية بالدينار العراقي</p>
                                                                                                      </div>
                                                                                                              </div>
                                                                                                                      <div className="bg-emerald-50 text-emerald-700 px-4 py-2 rounded-xl text-sm font-semibold border border-emerald-200 flex items-center gap-2">
                                                                                                                                <Wallet className="w-4 h-4" />
                                                                                                                                          الخزينة العامة نشطة
                                                                                                                                                  </div>
                                                                                                                                                        </div>

                                                                                                                                                              {/* مؤشرات الخزينة */}
                                                                                                                                                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                  <span className="text-slate-500 text-sm">سعر صرف الدولار المعتمد</span>
                                                                                                                                                                                                              <DollarSign className="w-5 h-5 text-emerald-600" />
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">153,500 د.ع</h3>
                                                                                                                                                                                                                                            <span className="text-emerald-600 text-xs mt-1 block">لكل 100 دولار أمريكي</span>
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                  <span className="text-slate-500 text-sm">سيولة الخزينة المتاحة</span>
                                                                                                                                                                                                                                                                                              <Wallet className="w-5 h-5 text-blue-600" />
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">145,200,000 د.ع</h3>
                                                                                                                                                                                                                                                                                                                            <span className="text-emerald-600 text-xs mt-1 block">رصيد آمن لتغطية العمليات</span>
                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                  <span className="text-slate-500 text-sm">التحويلات قيد التسوية</span>
                                                                                                                                                                                                                                                                                                                                                                              <TrendingUp className="w-5 h-5 text-amber-600" />
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">4,150,000 د.ع</h3>
                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-slate-400 text-xs mt-1 block">تتم معالجتها خلال ساعات</span>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                {/* جدول سجل الخزينة */}
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="font-bold text-slate-800 text-lg">سجل العمليات المالية والتحويلات النقدية</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full">جاهز للربط بقاعدة البيانات</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-8 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            سيتم جلب سجلات الإيداع والسحب وتسويات العملات مباشرة من جدول المعاملات المالية في Supabase...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                