// app/command-center/page.tsx
import Link from 'next/link';
import { Package, Store, Truck, ShieldCheck, TrendingUp, DollarSign } from 'lucide-react';

export default function CommandCenterHome() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة */}
                  <header className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div>
                                    <h1 className="text-2xl font-bold text-slate-800">مركز العمليات التنفيذي - جملتي</h1>
                                              <p className="text-slate-500 text-sm mt-1">نظرة شاملة وموحدة لإدارة الموردين، المحلات، والشحنات في السوق العراقي</p>
                                                      </div>
                                                              <div className="bg-emerald-50 text-emerald-700 px-4 py-2 rounded-xl text-sm font-semibold border border-emerald-200">
                                                                        النظام يعمل بكفاءة 🚀
                                                                                </div>
                                                                                      </header>

                                                                                            {/* بطاقات الانتقال السريع للأقسام الرئيسية (الهيكلية النهائية) */}
                                                                                                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
                                                                                                          
                                                                                                                  {/* قسم الجملة */}
                                                                                                                          <Link href="/command-center/wholesale" className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 hover:border-emerald-500 transition-all group">
                                                                                                                                    <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center mb-4 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                                                                                                                                                <Package className="w-6 h-6" />
                                                                                                                                                          </div>
                                                                                                                                                                    <h3 className="text-lg font-bold text-slate-800 mb-1">موردو الجملة</h3>
                                                                                                                                                                              <p className="text-slate-500 text-xs">إدارة المستودعات الكبرى، المخزون، وأسعار الجملة.</p>
                                                                                                                                                                                      </Link>

                                                                                                                                                                                              {/* قسم التجزئة */}
                                                                                                                                                                                                      <Link href="/command-center/retail" className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 hover:border-emerald-500 transition-all group">
                                                                                                                                                                                                                <div className="w-12 h-12 bg-amber-50 text-amber-600 rounded-xl flex items-center justify-center mb-4 group-hover:bg-amber-600 group-hover:text-white transition-colors">
                                                                                                                                                                                                                            <Store className="w-6 h-6" />
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                <h3 className="text-lg font-bold text-slate-800 mb-1">محلات التجزئة</h3>
                                                                                                                                                                                                                                                          <p className="text-slate-500 text-xs">متابعة طلبيات المحلات، الديون، وأرصدة التجار.</p>
                                                                                                                                                                                                                                                                  </Link>

                                                                                                                                                                                                                                                                          {/* قسم التوصيل */}
                                                                                                                                                                                                                                                                                  <Link href="/command-center/logistics" className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 hover:border-emerald-500 transition-all group">
                                                                                                                                                                                                                                                                                            <div className="w-12 h-12 bg-purple-50 text-purple-600 rounded-xl flex items-center justify-center mb-4 group-hover:bg-purple-600 group-hover:text-white transition-colors">
                                                                                                                                                                                                                                                                                                        <Truck className="w-6 h-6" />
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                            <h3 className="text-lg font-bold text-slate-800 mb-1">الخدمات اللوجستية</h3>
                                                                                                                                                                                                                                                                                                                                      <p className="text-slate-500 text-xs">حركة الشحنات الحية وتوزيع المناديب في المحافظات.</p>
                                                                                                                                                                                                                                                                                                                                              </Link>

                                                                                                                                                                                                                                                                                                                                                      {/* قسم الإدارة والمالية */}
                                                                                                                                                                                                                                                                                                                                                              <Link href="/command-center/administration" className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200 hover:border-emerald-500 transition-all group">
                                                                                                                                                                                                                                                                                                                                                                        <div className="w-12 h-12 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center mb-4 group-hover:bg-emerald-600 group-hover:text-white transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                    <ShieldCheck className="w-6 h-6" />
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-lg font-bold text-slate-800 mb-1">الإدارة والخزينة</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-slate-500 text-xs">الصلاحيات، أسعار الصرف، وتسوية المعاملات المالية.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>

                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* قسم المؤشرات السريعة (مساحة مخصصة للتحليلات لاحقاً) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <TrendingUp className="w-5 h-5 text-emerald-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        حالة النظام العامة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-4 bg-slate-50 rounded-xl border border-slate-100 text-slate-600 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  جاهز لربط قواعد بيانات Supabase وجلب مؤشرات المبيعات الحية لكل قسم...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      