// app/command-center/retail/credit/page.tsx
import Link from 'next/link';
import { CreditCard, ArrowRight, DollarSign, AlertCircle, CheckCircle2 } from 'lucide-react';

export default function RetailCreditPage() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة مع زر العودة */}
                  <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div className="flex items-center gap-4">
                                    <Link href="/command-center/retail" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                <ArrowRight className="w-5 h-5 text-slate-700" />
                                                          </Link>
                                                                    <div>
                                                                                <h1 className="text-2xl font-bold text-slate-800">إدارة الآجل والديون (التجزئة)</h1>
                                                                                            <p className="text-slate-500 text-sm mt-1">متابعة الأرصدة المستحقة، حدود التمويل، وتسويات الديون للمحلات</p>
                                                                                                      </div>
                                                                                                              </div>
                                                                                                                      <div className="bg-amber-50 text-amber-700 px-4 py-2 rounded-xl text-sm font-semibold border border-amber-200">
                                                                                                                                العملة: دينار عراقي (IQD)
                                                                                                                                        </div>
                                                                                                                                              </div>

                                                                                                                                                    {/* مؤشرات الديون والآجل */}
                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                  <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                            <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                        <span className="text-slate-500 text-sm">إجمالي الديون المستحقة</span>
                                                                                                                                                                                                    <CreditCard className="w-5 h-5 text-amber-600" />
                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                        <h3 className="text-2xl font-bold text-slate-800">18,500,000 د.ع</h3>
                                                                                                                                                                                                                                  <span className="text-amber-600 text-xs mt-1 block">تتطلب المتابعة والتحصيل</span>
                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                  <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                            <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                        <span className="text-slate-500 text-sm">تم سدادها هذا الأسبوع</span>
                                                                                                                                                                                                                                                                                    <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                        <h3 className="text-2xl font-bold text-slate-800">6,200,000 د.ع</h3>
                                                                                                                                                                                                                                                                                                                  <span className="text-emerald-600 text-xs mt-1 block">عمليات تسوية ناجحة</span>
                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                  <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                            <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                        <span className="text-slate-500 text-sm">حسابات متجاوزة الحد</span>
                                                                                                                                                                                                                                                                                                                                                                    <AlertCircle className="w-5 h-5 text-rose-600" />
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-2xl font-bold text-slate-800">3 محلات</h3>
                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-rose-600 text-xs mt-1 block">تم إيقاف الطلب الآجل مؤقتاً</span>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                      {/* جدول تفاصيل الديون */}
                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="font-bold text-slate-800 text-lg">سجل أرصدة المحلات والديون</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full">جاهز للربط بقاعدة البيانات</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-8 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  سيتم جلب تفاصيل المديونيات وأسقف التمويل لكل محل تجاري تلقائياً من جداول Supabase...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      