// app/command-center/retail/page.tsx
'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Store, ArrowRight, ShoppingBag, CreditCard, Loader2 } from 'lucide-react';
// تأكد من مسار عميل Supabase الخاص بك
import { createClient } from '@/utils/supabase/client'; 

export default function RetailManagementPage() {
  const [retailers, setRetailers] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
      const supabase = createClient();

        useEffect(() => {
            async function fetchRetailersData() {
                  try {
                          // جلب بيانات محلات التجزئة من قاعدة البيانات (مثال على جدول organizations أو users)
                                  const { data, error } = await supabase
                                            .from('organizations') // أو جدول التجار لديك
                                                      .select('*')
                                                                .eq('role', 'retail') // جلب محلات التجزئة فقط
                                                                          .limit(10);

                                                                                  if (error) {
                                                                                            console.error('خطأ في جلب بيانات المحلات:', error.message);
                                                                                                    } else if (data) {
                                                                                                              setRetailers(data);
                                                                                                                      }
                                                                                                                            } catch (err) {
                                                                                                                                    console.error('حدث خطأ غير متوقع:', err);
                                                                                                                                          } finally {
                                                                                                                                                  setLoading(false);
                                                                                                                                                        }
                                                                                                                                                            }

                                                                                                                                                                fetchRetailersData();
                                                                                                                                                                  }, [supabase]);

                                                                                                                                                                    return (
                                                                                                                                                                        <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
                                                                                                                                                                              {/* رأس الصفحة مع زر العودة */}
                                                                                                                                                                                    <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                            <div className="flex items-center gap-4">
                                                                                                                                                                                                      <Link href="/command-center" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                                                                                                                                                                                  <ArrowRight className="w-5 h-5 text-slate-700" />
                                                                                                                                                                                                                            </Link>
                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                  <h1 className="text-2xl font-bold text-slate-800">إدارة محلات التجزئة</h1>
                                                                                                                                                                                                                                                              <p className="text-slate-500 text-sm mt-1">متابعة طلبيات المحلات، الأرصدة، وإدارة حسابات التجار والديون الحية</p>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                        <div className="flex gap-3">
                                                                                                                                                                                                                                                                                                  <Link href="/command-center/retail/credit" className="bg-amber-600 hover:bg-amber-700 text-white px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 transition-colors">
                                                                                                                                                                                                                                                                                                              <CreditCard className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                          إدارة الآجل والديون
                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                        {/* إحصائيات سريعة */}
                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-slate-500 text-sm">المحلات النشطة</span>
                                                                                                                                                                                                                                                                                                                                                                                                        <Store className="w-5 h-5 text-amber-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-2xl font-bold text-slate-800">{retailers.length} محل</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-emerald-600 text-xs mt-1 block">متصلون عبر قاعدة البيانات</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-slate-500 text-sm">طلبات التجزئة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ShoppingBag className="w-5 h-5 text-blue-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-2xl font-bold text-slate-800">نشط</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-slate-400 text-xs mt-1 block">قيد المزامنة الفورية</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-slate-500 text-sm">العملة المعتمدة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-xs bg-emerald-100 text-emerald-800 px-2 py-0.5 rounded">دينار عراقي</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-2xl font-bold text-slate-800">IQD</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-slate-400 text-xs mt-1 block">تحديث آلي للمعاملات</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* جدول البيانات الحقيقي من Supabase */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="font-bold text-slate-800 text-lg">قائمة المحلات المسجلة (من قاعدة البيانات)</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-xs bg-emerald-50 text-emerald-700 px-3 py-1 rounded-full border border-emerald-200">متصل بـ Supabase</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="p-12 flex flex-col items-center justify-center text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Loader2 className="w-8 h-8 animate-spin text-amber-600 mb-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm">جاري جلب بيانات المحلات من السيرفر...</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : retailers.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-12 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              لا توجد محلات مسجلة حالياً في هذا الجدول، أو أن الاتصال ينتظر إضافة بيانات تجريبية.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="overflow-x-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <table className="w-full text-right border-collapse">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr className="bg-slate-50 border-b border-slate-100 text-slate-500 text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th className="p-4">اسم المحل / المؤسسة</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th className="p-4">الحالة</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <th className="p-4">تاريخ الانضمام</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tbody className="divide-y divide-slate-100 text-sm text-slate-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {retailers.map((item, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr key={index} className="hover:bg-slate-50/50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td className="p-4 font-semibold text-slate-900">{item.name || 'محل تجاري'}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="bg-emerald-50 text-emerald-700 px-2.5 py-1 rounded-lg text-xs">نشط</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td className="p-4 text-slate-500">{new Date(item.created_at || Date.now()).toLocaleDateString('ar-IQ')}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        