// app/command-center/logistics/zones/page.tsx
import Link from 'next/link';
import { MapPin, ArrowRight, Truck, Globe, Navigation } from 'lucide-react';

export default function LogisticsZonesPage() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة مع زر العودة */}
                  <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div className="flex items-center gap-4">
                                    <Link href="/command-center/logistics" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                <ArrowRight className="w-5 h-5 text-slate-700" />
                                                          </Link>
                                                                    <div>
                                                                                <h1 className="text-2xl font-bold text-slate-800">إدارة مناطق التغطية وأجور النقل</h1>
                                                                                            <p className="text-slate-500 text-sm mt-1">تحديد المحافظات، مسارات التوزيع، وأجور الشحنات للمندوبين</p>
                                                                                                      </div>
                                                                                                              </div>
                                                                                                                      <div className="bg-purple-50 text-purple-700 px-4 py-2 rounded-xl text-sm font-semibold border border-purple-200 flex items-center gap-2">
                                                                                                                                <Globe className="w-4 h-4" />
                                                                                                                                          تغطية عموم العراق
                                                                                                                                                  </div>
                                                                                                                                                        </div>

                                                                                                                                                              {/* مؤشرات المناطق */}
                                                                                                                                                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                  <span className="text-slate-500 text-sm">المحافظات المغطاة</span>
                                                                                                                                                                                                              <MapPin className="w-5 h-5 text-purple-600" />
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">15 محافظة</h3>
                                                                                                                                                                                                                                            <span className="text-emerald-600 text-xs mt-1 block">شبكة توصيل نشطة</span>
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                  <span className="text-slate-500 text-sm">متوسط تكلفة النقل</span>
                                                                                                                                                                                                                                                                                              <Truck className="w-5 h-5 text-blue-600" />
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">15,000 د.ع</h3>
                                                                                                                                                                                                                                                                                                                            <span className="text-slate-400 text-xs mt-1 block">للكرتون / الشحنة القياسية</span>
                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                  <span className="text-slate-500 text-sm">حالة المسارات</span>
                                                                                                                                                                                                                                                                                                                                                                              <Navigation className="w-5 h-5 text-emerald-600" />
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">مستقرة</h3>
                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-emerald-600 text-xs mt-1 block">بدون معوقات مرورية تذكر</span>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                {/* جدول أو محتوى المناطق */}
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="font-bold text-slate-800 text-lg">خريطة ومحافظات التوزيع الجغرافي</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full">جاهز للربط بقاعدة البيانات</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-8 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            سيتم ربط أسعار التوصيل ومناطق النفوذ للمندوبين بجداول النظام اللوجستي في Supabase...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                