// app/command-center/administration/page.tsx
import Link from 'next/link';
import { ShieldCheck, ArrowRight, DollarSign, Lock, UsersCheck, FileText } from 'lucide-react';

export default function AdministrationManagementPage() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة مع زر العودة */}
                  <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div className="flex items-center gap-4">
                                    <Link href="/command-center" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                <ArrowRight className="w-5 h-5 text-slate-700" />
                                                          </Link>
                                                                    <div>
                                                                                <h1 className="text-2xl font-bold text-slate-800">الإدارة العليا والخزينة</h1>
                                                                                            <p className="text-slate-500 text-sm mt-1">التحكم بصلاحيات النظام، أسعار الصرف الرسمية، وتسوية المعاملات المالية</p>
                                                                                                      </div>
                                                                                                              </div>
                                                                                                                      <div className="flex gap-3">
                                                                                                                                <Link href="/command-center/administration/finance" className="bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 transition-colors">
                                                                                                                                            <DollarSign className="w-4 h-4" />
                                                                                                                                                        إدارة الخزينة والعملات
                                                                                                                                                                  </Link>
                                                                                                                                                                          </div>
                                                                                                                                                                                </div>

                                                                                                                                                                                      {/* إحصائيات سريعة لقسم الإدارة */}
                                                                                                                                                                                            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">حالة الأمان والصلاحيات</span>
                                                                                                                                                                                                                                      <ShieldCheck className="w-5 h-5 text-emerald-600" />
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">مؤمن بالكامل</h3>
                                                                                                                                                                                                                                                                    <span className="text-emerald-600 text-xs mt-1 block">تشفير سياسات Supabase نشط</span>
                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">الموافقات المعلقة</span>
                                                                                                                                                                                                                                                                                                                      <UsersCheck className="w-5 h-5 text-amber-600" />
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">7 طلبات</h3>
                                                                                                                                                                                                                                                                                                                                                    <span className="text-slate-400 text-xs mt-1 block">بانتظار موافقة الإدارة</span>
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">إجمالي السيولة المسواة</span>
                                                                                                                                                                                                                                                                                                                                                                                                      <DollarSign className="w-5 h-5 text-blue-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">84,500,000 د.ع</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-emerald-600 text-xs mt-1 block">خلال هذا الأسبوع</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* جدول أو سجل العمليات الإدارية (قيد الربط مع Supabase) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="font-bold text-slate-800 text-lg">سجل العمليات الإدارية والمالية</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full">جاهز للربط بالقاعدة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="p-8 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    سيتم عرض سجل التدقيق الصلاحيات (Audit Logs) وتحديثات خزينة المنصة تلقائياً من قاعدة بيانات Supabase...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        up