// app/command-center/wholesale/page.tsx
import Link from 'next/link';
import { Package, ArrowRight, PlusCircle, Layers, DollarSign } from 'lucide-react';

export default function WholesaleManagementPage() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة مع زر العودة */}
                  <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div className="flex items-center gap-4">
                                    <Link href="/command-center" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                <ArrowRight className="w-5 h-5 text-slate-700" />
                                                          </Link>
                                                                    <div>
                                                                                <h1 className="text-2xl font-bold text-slate-800">إدارة موردو الجملة</h1>
                                                                                            <p className="text-slate-500 text-sm mt-1">متابعة المستودعات الكبرى، المخزون، وإدارة كتالوج أسعار الجملة</p>
                                                                                                      </div>
                                                                                                              </div>
                                                                                                                      <div className="flex gap-3">
                                                                                                                                <Link href="/command-center/wholesale/catalog" className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 transition-colors">
                                                                                                                                            <Layers className="w-4 h-4" />
                                                                                                                                                        إدارة الكتالوج
                                                                                                                                                                  </Link>
                                                                                                                                                                          </div>
                                                                                                                                                                                </div>

                                                                                                                                                                                      {/* إحصائيات سريعة لقسم الجملة */}
                                                                                                                                                                                            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">إجمالي الموردين</span>
                                                                                                                                                                                                                                      <Package className="w-5 h-5 text-blue-600" />
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">24 مورد</h3>
                                                                                                                                                                                                                                                                    <span className="text-emerald-600 text-xs mt-1 block">نشطون في مختلف المحافظات</span>
                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">حجم المخزون الكلي</span>
                                                                                                                                                                                                                                                                                                                      <Layers className="w-5 h-5 text-emerald-600" />
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">1,420 صنف</h3>
                                                                                                                                                                                                                                                                                                                                                    <span className="text-slate-400 text-xs mt-1 block">متوفر في المستودعات الرئيسية</span>
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">سعر الصرف المعتمد</span>
                                                                                                                                                                                                                                                                                                                                                                                                      <DollarSign className="w-5 h-5 text-amber-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">153,500 د.ع</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-slate-400 text-xs mt-1 block">لكل 100 دولار أمريكي</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* جدول عرض الموردين (قيد الربط مع Supabase) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="font-bold text-slate-800 text-lg">قائمة الموردين الكبرى</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full">جاهز للربط بالقاعدة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="p-8 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    سيتم جلب بيانات الموردين والمستودعات تلقائياً من جدول الموردين في قاعدة بيانات Supabase...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        