'use client';
import { useRouter } from 'next/navigation';
import { Store, Truck, DollarSign, Users, Settings, Package, ShoppingCart, ShieldCheck, ArrowUpLeft } from 'lucide-react';

export default function HomeHub() {
  const router = useRouter();

    const sections = [
        {
              title: 'بوابة التجزئة والمتاجر',
                    description: 'إدارة السلة، الكتالوج، الطلبات، وحسابات المتاجر الفرعية',
                          path: '/retailer-core',
                                icon: <Store size={22} className="text-indigo-400" />,
                                      color: 'border-indigo-500/20 bg-indigo-500/10'
                                          },
                                              {
                                                    title: 'بوابة الموردين والجملة',
                                                          description: 'إدارة الطلبات الواردة، كتالوج المورد، والمالية الخاصة بالموردين',
                                                                path: '/supplier-central',
                                                                      icon: <Package size={22} className="text-emerald-400" />,
                                                                            color: 'border-emerald-500/20 bg-emerald-500/10'
                                                                                },
                                                                                    {
                                                                                          title: 'المركز المالي والحسابات',
                                                                                                description: 'متابعة الإيرادات، الأرباح التقديرية، والتقارير النقدية بالدينار العراقي',
                                                                                                      path: '/financials',
                                                                                                            icon: <DollarSign size={22} className="text-amber-400" />,
                                                                                                                  color: 'border-amber-500/20 bg-amber-500/10'
                                                                                                                      },
                                                                                                                          {
                                                                                                                                title: 'إدارة المخزون',
                                                                                                                                      description: 'مراقبة المستودعات، الكميات المتوفرة، وتنبيهات قرب نفاذ البضائع',
                                                                                                                                            path: '/inventory',
                                                                                                                                                  icon: <ShoppingCart size={22} className="text-blue-400" />,
                                                                                                                                                        color: 'border-blue-500/20 bg-blue-500/10'
                                                                                                                                                            },
                                                                                                                                                                {
                                                                                                                                                                      title: 'العمليات اللوجستية والشحن',
                                                                                                                                                                            description: 'تدفق الشحنات الحية، السجلات المؤرشفة، وتوزيع مهام التوصيل للمناديب',
                                                                                                                                                                                  path: '/logistics-flow',
                                                                                                                                                                                        icon: <Truck size={22} className="text-purple-400" />,
                                                                                                                                                                                              color: 'border-purple-500/20 bg-purple-500/10'
                                                                                                                                                                                                  },
                                                                                                                                                                                                      {
                                                                                                                                                                                                            title: 'إدارة النظام والصلاحيات',
                                                                                                                                                                                                                  description: 'متابعة المستخدمين، إعدادات الخوادم، وصحة الاتصال بقاعدة البيانات',
                                                                                                                                                                                                                        path: '/system',
                                                                                                                                                                                                                              icon: <Settings size={22} className="text-rose-400" />,
                                                                                                                                                                                                                                    color: 'border-rose-500/20 bg-rose-500/10'
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                          ];

                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic p-6 md:p-12" dir="rtl">
                                                                                                                                                                                                                                                      <div className="max-w-5xl mx-auto space-y-8">
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                      {/* الترويسة الرئيسية */}
                                                                                                                                                                                                                                                                              <div className="bg-slate-900/80 border border-slate-800 p-8 rounded-3xl backdrop-blur-xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4 shadow-2xl">
                                                                                                                                                                                                                                                                                        <div className="space-y-2">
                                                                                                                                                                                                                                                                                                    <div className="inline-flex items-center gap-2 bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 px-3 py-1 rounded-full text-[11px] font-bold">
                                                                                                                                                                                                                                                                                                                  <ShieldCheck size={14} /> السوق العراقي الموحد
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                          <h1 className="text-xl md:text-2xl font-black text-white">منصة جملتي التجارية</h1>
                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs text-slate-400">اختر القسم الذي تريد الانتقال إليه لإدارة العمليات بشكل مباشر وفوري:</p>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-slate-950 px-4 py-3 rounded-2xl border border-slate-800 text-left">
                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-[10px] text-slate-500">حالة النظام</p>
                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs font-bold text-emerald-400 flex items-center gap-1.5 mt-0.5">
                                                                                                                                                                                                                                                                                                                                                                                                                <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse"></span> جاهز للتشغيل
                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* شبكة الأقسام والواجهات */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {sections.map((sec, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={index}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => router.push(sec.path)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="bg-slate-900/90 border border-slate-800 hover:border-indigo-500/50 p-6 rounded-3xl cursor-pointer transition-all duration-300 hover:shadow-xl hover:-translate-y-1 group flex flex-col justify-between space-y-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className={`w-12 h-12 rounded-2xl grid place-items-center border ${sec.color}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {sec.icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-sm font-bold text-white group-hover:text-indigo-400 transition">{sec.title}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[11px] text-slate-400 mt-1 leading-relaxed">{sec.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center justify-between pt-4 border-t border-slate-800/80 text-slate-400 text-xs font-semibold group-hover:text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>استعراض الواجهة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ArrowUpLeft size={16} className="group-hover:-translate-x-1 group-hover:-translate-y-1 transition text-indigo-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
