'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { CheckSquare, ArrowRight, Plus, AlertCircle, UserCheck } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';

export default function LogisticsTasks() {
  const router = useRouter();
    const [tasks, setTasks] = useState<any[]>([]);
      const [loading, setLoading] = useState(false);

        useEffect(() => {
            fetchTasks();
              }, []);

                const fetchTasks = async () => {
                    try {
                          setLoading(true);
                                const { data, error } = await supabase.from('orders').select('*');
                                      if (error) throw error;
                                            if (data) setTasks(data);
                                                } catch (err) {
                                                      console.error(err);
                                                          } finally {
                                                                setLoading(false);
                                                                    }
                                                                      };

                                                                        return (
                                                                            <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic" dir="rtl">
                                                                                  <header className="bg-slate-900/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
                                                                                          <div className="flex items-center gap-3">
                                                                                                    <button onClick={() => router.back()} className="h-10 w-10 rounded-xl bg-slate-800 text-slate-300 hover:text-white grid place-items-center transition">
                                                                                                                <ArrowRight size={20} />
                                                                                                                          </button>
                                                                                                                                    <div>
                                                                                                                                                <h1 className="text-sm font-black text-white">المهام والعمليات اللوجستية</h1>
                                                                                                                                                            <p className="text-[11px] text-slate-400">توزيع مهام التجهيز، التحميل، والتسليم للمناديب</p>
                                                                                                                                                                      </div>
                                                                                                                                                                              </div>
                                                                                                                                                                                    </header>

                                                                                                                                                                                          <main className="max-w-6xl mx-auto p-6 space-y-6">
                                                                                                                                                                                                  <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
                                                                                                                                                                                                            <h2 className="text-sm font-bold text-white flex items-center gap-2">
                                                                                                                                                                                                                        <CheckSquare size={18} className="text-emerald-400" />
                                                                                                                                                                                                                                    قائمة مهام الأسطول والمناديب
                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                        {loading ? (
                                                                                                                                                                                                                                                                    <div className="text-center py-20 text-slate-500 text-xs">جاري تحميل المهام...</div>
                                                                                                                                                                                                                                                                              ) : tasks.length === 0 ? (
                                                                                                                                                                                                                                                                                          <div className="text-center py-20 text-slate-500 text-xs">لا توجد مهام لوجستية معلقة حالياً.</div>
                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                              {tasks.map((task) => (
                                                                                                                                                                                                                                                                                                                                              <div key={task.id} className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                    <div className="h-10 w-10 rounded-xl bg-emerald-500/10 text-emerald-400 grid place-items-center border border-emerald-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                          <UserCheck size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs font-bold text-white">مهمة تجهيز طلب #{task.id.slice(0, 8)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[10px] text-slate-400 mt-0.5">الحالة: جاهزة للتوزيع</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="bg-indigo-600 hover:bg-indigo-500 text-white px-3 py-1.5 rounded-xl text-xs font-bold transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          إتمام المهمة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    