// app/command-center/logistics/page.tsx
import Link from 'next/link';
import { Truck, ArrowRight, MapPin, Navigation, Clock } from 'lucide-react';

export default function LogisticsManagementPage() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة مع زر العودة */}
                  <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div className="flex items-center gap-4">
                                    <Link href="/command-center" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                <ArrowRight className="w-5 h-5 text-slate-700" />
                                                          </Link>
                                                                    <div>
                                                                                <h1 className="text-2xl font-bold text-slate-800">الخدمات اللوجستية والشحن</h1>
                                                                                            <p className="text-slate-500 text-sm mt-1">متابعة حركة الشحنات الحية، أداء المناديب، وتوزيع خطوط السير في المحافظات</p>
                                                                                                      </div>
                                                                                                              </div>
                                                                                                                      <div className="flex gap-3">
                                                                                                                                <Link href="/command-center/logistics/zones" className="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 transition-colors">
                                                                                                                                            <MapPin className="w-4 h-4" />
                                                                                                                                                        تحديد مناطق التغطية
                                                                                                                                                                  </Link>
                                                                                                                                                                          </div>
                                                                                                                                                                                </div>

                                                                                                                                                                                      {/* إحصائيات سريعة لقسم الشحن */}
                                                                                                                                                                                            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">الشحنات بالطريق الآن</span>
                                                                                                                                                                                                                                      <Truck className="w-5 h-5 text-purple-600" />
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">32 شحنة</h3>
                                                                                                                                                                                                                                                                    <span className="text-emerald-600 text-xs mt-1 block">تتحرك بين المحافظات</span>
                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">المناديب النشطون</span>
                                                                                                                                                                                                                                                                                                                      <Navigation className="w-5 h-5 text-blue-600" />
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">14 مندوب</h3>
                                                                                                                                                                                                                                                                                                                                                    <span className="text-slate-400 text-xs mt-1 block">متصلون عبر نظام التتبع</span>
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-slate-500 text-sm">متوسط وقت التوصيل</span>
                                                                                                                                                                                                                                                                                                                                                                                                      <Clock className="w-5 h-5 text-amber-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-2xl font-bold text-slate-800">24 ساعة</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-emerald-600 text-xs mt-1 block">أسرع بنسبة 15% عن السابق</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* جدول أو خريطة متابعة الشحنات (قيد الربط مع Supabase) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="font-bold text-slate-800 text-lg">حركة الشحنات الحية في المحافظات</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full">جاهز للربط بالقاعدة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="p-8 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    سيتم تحديث حالات الشحنات ومواقعها الجغرافية تلقائياً من جدول الشحنات في قاعدة بيانات Supabase...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        