'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { FileText, ArrowRight, ShieldCheck, Calendar, Search } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';

export default function LogisticsRecords() {
  const router = useRouter();
    const [records, setRecords] = useState<any[]>([]);
      const [loading, setLoading] = useState(false);

        useEffect(() => {
            fetchRecords();
              }, []);

                const fetchRecords = async () => {
                    try {
                          setLoading(true);
                                const { data, error } = await supabase.from('orders').select('*');
                                      if (error) throw error;
                                            if (data) setRecords(data);
                                                } catch (err) {
                                                      console.error(err);
                                                          } finally {
                                                                setLoading(false);
                                                                    }
                                                                      };

                                                                        return (
                                                                            <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic" dir="rtl">
                                                                                  <header className="bg-slate-900/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
                                                                                          <div className="flex items-center gap-3">
                                                                                                    <button onClick={() => router.back()} className="h-10 w-10 rounded-xl bg-slate-800 text-slate-300 hover:text-white grid place-items-center transition">
                                                                                                                <ArrowRight size={20} />
                                                                                                                          </button>
                                                                                                                                    <div>
                                                                                                                                                <h1 className="text-sm font-black text-white">السجلات اللوجستية للأرشيف</h1>
                                                                                                                                                            <p className="text-[11px] text-slate-400">أرشفة عمليات النقل، بوليصات الشحن، والتسليمات السابقة</p>
                                                                                                                                                                      </div>
                                                                                                                                                                              </div>
                                                                                                                                                                                    </header>

                                                                                                                                                                                          <main className="max-w-6xl mx-auto p-6 space-y-6">
                                                                                                                                                                                                  <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
                                                                                                                                                                                                            <h2 className="text-sm font-bold text-white flex items-center gap-2">
                                                                                                                                                                                                                        <FileText size={18} className="text-indigo-400" />
                                                                                                                                                                                                                                    سجل العمليات المؤرشفة
                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                        {loading ? (
                                                                                                                                                                                                                                                                    <div className="text-center py-20 text-slate-500 text-xs">جاري تحميل السجلات...</div>
                                                                                                                                                                                                                                                                              ) : records.length === 0 ? (
                                                                                                                                                                                                                                                                                          <div className="text-center py-20 text-slate-500 text-xs">لا توجد سجلات لوجستية مؤرشفة حالياً.</div>
                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                              {records.map((rec) => (
                                                                                                                                                                                                                                                                                                                                              <div key={rec.id} className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                    <div className="h-10 w-10 rounded-xl bg-indigo-500/10 text-indigo-400 grid place-items-center border border-indigo-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                          <ShieldCheck size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs font-bold text-white">بوليصة شحن - #{rec.id.slice(0, 8)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[10px] text-slate-400 mt-0.5">الحالة المؤرشفة: مكتملة الأركان</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-xs text-slate-400">{rec.total_amount || 0} د.ع</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              