'use client';

import React, { memo, useMemo } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import {
  LayoutDashboard,
    Package,
      ShoppingCart,
        ShieldCheck,
          Users,
            UserCircle,
              Home,
                Grid3X3,
                  ClipboardList,
                    Wallet,
                      Settings,
                        CreditCard,
                        } from 'lucide-react';

                        export interface BottomNavItem {
                          id: string;
                            label: string;
                              icon: React.ElementType;
                                href: string;
                                  badge?: number;
                                  }

                                  const retailerNav: BottomNavItem[] = [
                                    { id: 'r-home', label: 'الرئيسية', icon: Home, href: '/retailer-home' },
                                      { id: 'r-catalog', label: 'الأقسام', icon: Grid3X3, href: '/retailer-catalog' },
                                        { id: 'r-orders', label: 'السلة', icon: ShoppingCart, href: '/retailer-orders' },
                                          { id: 'r-profile', label: 'حسابي', icon: UserCircle, href: '/retailer-profile' },
                                          ];

                                          const supplierNav: BottomNavItem[] = [
                                            { id: 's-dashboard', label: 'الرئيسية', icon: LayoutDashboard, href: '/supplier-dashboard' },
                                              { id: 's-catalog', label: 'الكتالوج', icon: Package, href: '/supplier-catalog' },
                                                { id: 's-orders', label: 'الطلبات', icon: ClipboardList, href: '/supplier-incoming-orders', badge: 2 },
                                                  { id: 's-finance', label: 'المالية', icon: Wallet, href: '/supplier-finance' },
                                                  ];

                                                  const adminNav: BottomNavItem[] = [
                                                    { id: 'a-hub', label: 'التحكم', icon: ShieldCheck, href: '/admin-hub' },
                                                      { id: 'a-users', label: 'الحسابات', icon: Users, href: '/admin-users' },
                                                        { id: 'a-transactions', label: 'المعاملات', icon: CreditCard, href: '/admin-transactions' },
                                                          { id: 'a-settings', label: 'الإعدادات', icon: Settings, href: '/admin-settings' },
                                                          ];

                                                          const navByRole: Record<string, BottomNavItem[]> = {
                                                            retailer: retailerNav,
                                                              branch: retailerNav,
                                                                supplier: supplierNav,
                                                                  admin: adminNav,
                                                                  };

                                                                  export const BottomNavBar = memo(function BottomNavBar() {
                                                                    const pathname = usePathname();
                                                                      const { user } = useAuth();

                                                                        // تحديد الدور بناءً على بيانات المستخدم أو المسار الحالي
                                                                          const role = useMemo(() => {
                                                                              if (user?.role) {
                                                                                    return user.role;
                                                                                        }
                                                                                            if (pathname?.startsWith('/admin')) return 'admin';
                                                                                                if (pathname?.startsWith('/supplier')) return 'supplier';
                                                                                                    return 'retailer';
                                                                                                      }, [user?.role, pathname]);

                                                                                                        const items = navByRole[role] || retailerNav;

                                                                                                          const isActive = (href: string) => {
                                                                                                              if (!pathname) return false;
                                                                                                                  if (href === '/' || href === '/retailer-home') {
                                                                                                                        return pathname === href || pathname === '/';
                                                                                                                            }
                                                                                                                                return pathname.startsWith(href);
                                                                                                                                  };

                                                                                                                                    return (
                                                                                                                                        <nav
                                                                                                                                              className="fixed bottom-0 left-0 right-0 z-40 bg-card/90 backdrop-blur-md border-t border-border/70 lg:hidden shadow-lg transition-all duration-200"
                                                                                                                                                    style={{ paddingBottom: 'env(safe-area-inset-bottom, 0px)' }}
                                                                                                                                                          dir="rtl"
                                                                                                                                                              >
                                                                                                                                                                    <div className="flex items-stretch h-16 max-w-md mx-auto px-1">
                                                                                                                                                                            {items.map((item) => {
                                                                                                                                                                                      const NavIcon = item.icon;
                                                                                                                                                                                                const active = isActive(item.href);

                                                                                                                                                                                                          return (
                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                    key={item.id}
                                                                                                                                                                                                                                                  href={item.href}
                                                                                                                                                                                                                                                                className={`
                                                                                                                                                                                                                                                                                flex-1 flex flex-col items-center justify-center gap-1 relative select-none
                                                                                                                                                                                                                                                                                                transition-all duration-200 active:scale-95
                                                                                                                                                                                                                                                                                                                ${active ? 'text-primary' : 'text-muted-foreground hover:text-foreground'}
                                                                                                                                                                                                                                                                                                                              `}
                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                        {/* Active Indicator Line */}
                                                                                                                                                                                                                                                                                                                                                                      {active && (
                                                                                                                                                                                                                                                                                                                                                                                      <span className="absolute top-0 left-1/2 -translate-x-1/2 w-10 h-0.5 bg-primary rounded-b-full shadow-xs" />
                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Icon & Badge Container */}
                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="relative flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <NavIcon
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  size={21}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    strokeWidth={active ? 2.3 : 1.7}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={`transition-transform duration-200 ${active ? 'scale-105' : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.badge && item.badge > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="absolute -top-1.5 -right-2 bg-rose-500 text-white text-[10px] font-bold rounded-full h-4 min-w-[16px] px-1 flex items-center justify-center tabular-nums leading-none shadow-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {item.badge > 9 ? '9+' : item.badge}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Label */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={`text-[10px] font-arabic leading-none tracking-tight ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          active ? 'font-bold' : 'font-medium'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                BottomNavBar.displayName = 'BottomNavBar';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default BottomNavBar;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                