// app/supplier-logistics/page.tsx
'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { ShoppingBag, ArrowRight, CheckCircle, Clock, AlertCircle, Truck } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/lib/supabase/client';

export default function SupplierLogistics() {
  const router = useRouter();
    const { signOut } = useAuth();

      const [orders, setOrders] = useState<any[]>([]);
        const [loading, setLoading] = useState(false);
          const [error, setError] = useState('');

            useEffect(() => {
                fetchOrders();
                  }, []);

                    const fetchOrders = async () => {
                        try {
                              setLoading(true);
                                    const { data, error: ordErr } = await supabase.from('orders').select('*');
                                          if (ordErr) throw ordErr;
                                                if (data) setOrders(data);
                                                    } catch (err: any) {
                                                          setError('فشل في جلب طلبات الفروع الواردة.');
                                                              } finally {
                                                                    setLoading(false);
                                                                        }
                                                                          };

                                                                            const handleUpdateOrderStatus = async (orderId: string, newStatus: string) => {
                                                                                try {
                                                                                      const { error: updateErr } = await supabase
                                                                                              .from('orders')
                                                                                                      .update({ status: newStatus })
                                                                                                              .eq('id', orderId);

                                                                                                                    if (updateErr) throw updateErr;
                                                                                                                          fetchOrders();
                                                                                                                              } catch (err: any) {
                                                                                                                                    setError('فشل في تحديث حالة الطلب.');
                                                                                                                                        }
                                                                                                                                          };

                                                                                                                                            return (
                                                                                                                                                <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic" dir="rtl">
                                                                                                                                                      {/* الشريط العلوي */}
                                                                                                                                                            <header className="bg-slate-900/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                              <button
                                                                                                                                                                                          onClick={() => router.push('/supplier-central')}
                                                                                                                                                                                                      className="h-10 w-10 rounded-xl bg-slate-800 text-slate-300 hover:text-white grid place-items-center transition"
                                                                                                                                                                                                                >
                                                                                                                                                                                                                            <ArrowRight size={20} />
                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                            <h1 className="text-sm font-black text-white">إدارة طلبات الفروع واللوجستيات</h1>
                                                                                                                                                                                                                                                                        <p className="text-[11px] text-slate-400">متابعة شحنات محلات التجزئة واعتماد الطلبيات</p>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                                                                                      {/* المحتوى الرئيسي */}
                                                                                                                                                                                                                                                                                                            <main className="max-w-6xl mx-auto p-6 space-y-6">
                                                                                                                                                                                                                                                                                                                    <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                          <h2 className="text-sm font-bold text-white flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                        <ShoppingBag size={18} className="text-emerald-400" />
                                                                                                                                                                                                                                                                                                                                                                      الطلبات الواردة من شبكة التجزئة ({orders.length})
                                                                                                                                                                                                                                                                                                                                                                                  </h2>
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                      {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-rose-500/10 border border-rose-500/30 text-rose-400 p-3 rounded-xl text-xs flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                <AlertCircle size={16} className="shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>{error}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-center py-20 text-slate-500 text-xs">جاري تحميل الطلبات...</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : orders.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-center py-20 text-slate-500 text-xs">لا توجد طلبات واردة من الفروع حتى الآن.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {orders.map((ord) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={ord.id} className="bg-slate-950/80 border border-slate-800 p-5 rounded-2xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="space-y-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-xs font-bold text-white">طلب رقم: #{ord.id.slice(0, 8)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-[10px] bg-slate-900 px-2.5 py-1 rounded-lg border border-slate-800 text-slate-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              الحالة: <strong className="text-amber-400">{ord.status || 'قيد المعالجة'}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs font-bold text-emerald-400 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  المبلغ الإجمالي: {ord.total_amount || 0} د.ع
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2 w-full md:w-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => handleUpdateOrderStatus(ord.id, 'مقبول وجاري التجهيز')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="flex-1 md:flex-none bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/20 px-4 py-2 rounded-xl text-xs font-semibold transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    تجهيز الطلب
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => handleUpdateOrderStatus(ord.id, 'تم التسليم للمندوب')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="flex-1 md:flex-none bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 border border-blue-500/20 px-4 py-2 rounded-xl text-xs font-semibold transition flex items-center justify-center gap-1.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Truck size={14} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        تسليم للتوصيل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      