'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Truck, ArrowRight, MapPin, Navigation, Clock, CheckCircle2 } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';

export default function LogisticsFlow() {
  const router = useRouter();
    const [shipments, setShipments] = useState<any[]>([]);
      const [loading, setLoading] = useState(false);

        useEffect(() => {
            fetchShipments();
              }, []);

                const fetchShipments = async () => {
                    try {
                          setLoading(true);
                                const { data, error } = await supabase.from('orders').select('*');
                                      if (error) throw error;
                                            if (data) setShipments(data);
                                                } catch (err) {
                                                      console.error(err);
                                                          } finally {
                                                                setLoading(false);
                                                                    }
                                                                      };

                                                                        return (
                                                                            <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic" dir="rtl">
                                                                                  <header className="bg-slate-900/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
                                                                                          <div className="flex items-center gap-3">
                                                                                                    <button onClick={() => router.back()} className="h-10 w-10 rounded-xl bg-slate-800 text-slate-300 hover:text-white grid place-items-center transition">
                                                                                                                <ArrowRight size={20} />
                                                                                                                          </button>
                                                                                                                                    <div>
                                                                                                                                                <h1 className="text-sm font-black text-white">تدفق الشحنات وحركة التوصيل</h1>
                                                                                                                                                            <p className="text-[11px] text-slate-400">متابعة خطوط السير والمناديب في المحافظات</p>
                                                                                                                                                                      </div>
                                                                                                                                                                              </div>
                                                                                                                                                                                    </header>

                                                                                                                                                                                          <main className="max-w-6xl mx-auto p-6 space-y-6">
                                                                                                                                                                                                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                                                                                                                                                                                            <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                        <div className="h-12 w-12 rounded-2xl bg-amber-500/10 text-amber-400 grid place-items-center border border-amber-500/20">
                                                                                                                                                                                                                                      <Truck size={22} />
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                            <p className="text-xs text-slate-400">شحنات بالطريق</p>
                                                                                                                                                                                                                                                                                          <p className="text-lg font-black text-amber-400 mt-0.5">{shipments.length}</p>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                          <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                      <div className="h-12 w-12 rounded-2xl bg-emerald-500/10 text-emerald-400 grid place-items-center border border-emerald-500/20">
                                                                                                                                                                                                                                                                                                                                                    <CheckCircle2 size={22} />
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs text-slate-400">تم التوصيل بنجاح</p>
                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-lg font-black text-emerald-400 mt-0.5">0</p>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="h-12 w-12 rounded-2xl bg-indigo-500/10 text-indigo-400 grid place-items-center border border-indigo-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Navigation size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-slate-400">حالة الأسطول</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-lg font-black text-indigo-400 mt-0.5">نشط</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-sm font-bold text-white flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Truck size={18} className="text-amber-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              خريطة التدفق الحي للشحنات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-center py-20 text-slate-500 text-xs">جاري تحميل تدفق الشحنات...</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : shipments.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-center py-20 text-slate-500 text-xs">لا توجد شحنات نشطة حالياً في التدفق.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {shipments.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={item.id} className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="h-10 w-10 rounded-xl bg-amber-500/10 text-amber-400 grid place-items-center border border-amber-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <MapPin size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs font-bold text-white">طلب رقم #{item.id.slice(0, 8)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[10px] text-slate-400 mt-0.5">المبلغ: {item.total_amount || 0} د.ع</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-xs bg-amber-500/10 text-amber-400 px-3 py-1 rounded-xl border border-amber-500/20">قيد التوصيل</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        