// app/command-center/wholesale/catalog/page.tsx
import Link from 'next/link';
import { Layers, ArrowRight, PackagePlus, Tag, DollarSign } from 'lucide-react';

export default function WholesaleCatalogPage() {
  return (
      <div className="p-6 bg-slate-50 min-h-screen font-arabic" dir="rtl">
            {/* رأس الصفحة مع زر العودة */}
                  <div className="flex justify-between items-center mb-8 bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                          <div className="flex items-center gap-4">
                                    <Link href="/command-center/wholesale" className="p-2 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors">
                                                <ArrowRight className="w-5 h-5 text-slate-700" />
                                                          </Link>
                                                                    <div>
                                                                                <h1 className="text-2xl font-bold text-slate-800">إدارة كتالوج الجملة</h1>
                                                                                            <p className="text-slate-500 text-sm mt-1">إدارة المنتجات الكبرى، تحديث أسعار الجملة، ومراقبة الكميات في المستودعات</p>
                                                                                                      </div>
                                                                                                              </div>
                                                                                                                      <div className="bg-blue-50 text-blue-700 px-4 py-2 rounded-xl text-sm font-semibold border border-blue-200 flex items-center gap-2">
                                                                                                                                <PackagePlus className="w-4 h-4" />
                                                                                                                                          إضافة منتج جديد
                                                                                                                                                  </div>
                                                                                                                                                        </div>

                                                                                                                                                              {/* مؤشرات الكتالوج */}
                                                                                                                                                                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                  <span className="text-slate-500 text-sm">إجمالي الأصناف بالكتالوج</span>
                                                                                                                                                                                                              <Layers className="w-5 h-5 text-blue-600" />
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">1,420 صنف</h3>
                                                                                                                                                                                                                                            <span className="text-emerald-600 text-xs mt-1 block">محدثة حسب الأسعار الرسمية</span>
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                  <span className="text-slate-500 text-sm">أصناف نفذت من المخزون</span>
                                                                                                                                                                                                                                                                                              <Tag className="w-5 h-5 text-rose-600" />
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">12 صنف</h3>
                                                                                                                                                                                                                                                                                                                            <span className="text-rose-600 text-xs mt-1 block">بانتظار توريد جديد</span>
                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between items-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                  <span className="text-slate-500 text-sm">متوسط هامش الربح</span>
                                                                                                                                                                                                                                                                                                                                                                              <DollarSign className="w-5 h-5 text-emerald-600" />
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-2xl font-bold text-slate-800">14.5%</h3>
                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-emerald-600 text-xs mt-1 block">مستقر ضمن السوق العراقي</span>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                {/* جدول عرض المنتجات */}
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="font-bold text-slate-800 text-lg">قائمة أصناف الجملة الكبرى</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-xs bg-slate-100 text-slate-600 px-3 py-1 rounded-full">جاهز للربط بـ Supabase</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="p-8 text-center text-slate-400 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            سيتم جلب بيانات المنتجات والأسعار بالتفصيل من جداول المستودعات والمخزون في قاعدة البيانات...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                