'use client';

import { createClient } from '@/lib/supabase/client';

export interface CommissionEntry {
  id: string;
    orderId: string;
      orderDate: string;
        retailerName: string;
          orderTotal: number;
            commission: number;
              createdAt: string;
              }

              export interface LedgerEntry {
                id: string;
                  entryDate: string;
                    supplierId: string;
                      supplierName: string;
                        entryType: 'order' | 'payment' | 'adjustment';
                          description: string;
                            amount: number;
                              direction: 'debit' | 'credit';
                                balance: number;
                                  orderId?: string;
                                    paymentMethod?: string;
                                      status: 'completed' | 'pending' | 'overdue';
                                      }

                                      function isSchemaError(error: any): boolean {
                                        if (!error) return false;
                                          if (error.code && typeof error.code === 'string') {
                                              const cls = error.code.substring(0, 2);
                                                  if (cls === '42' || cls === '08') return true;
                                                      if (cls === '23') return false;
                                                        }
                                                          return false;
                                                          }

                                                          function toCommission(row: any): CommissionEntry {
                                                            return {
                                                                id: row.id ?? '',
                                                                    orderId: row.order_id ?? '',
                                                                        orderDate: row.order_date ?? row.created_at ?? new Date().toISOString(),
                                                                            retailerName: row.retailer_name ?? 'متجر غير معروف',
                                                                                orderTotal: Number(row.order_total ?? 0),
                                                                                    commission: Number(row.commission ?? 0),
                                                                                        createdAt: row.created_at ?? new Date().toISOString(),
                                                                                          };
                                                                                          }

                                                                                          function toLedger(row: any): LedgerEntry {
                                                                                            return {
                                                                                                id: row.id ?? '',
                                                                                                    entryDate: row.entry_date ?? row.created_at ?? new Date().toISOString(),
                                                                                                        supplierId: row.supplier_id ?? '',
                                                                                                            supplierName: row.supplier_name ?? 'مورد غير معروف',
                                                                                                                entryType: row.entry_type ?? 'order',
                                                                                                                    description: row.description ?? '',
                                                                                                                        amount: Number(row.amount ?? 0),
                                                                                                                            direction: row.direction ?? 'debit',
                                                                                                                                balance: Number(row.balance ?? 0),
                                                                                                                                    orderId: row.order_id ?? '',
                                                                                                                                        paymentMethod: row.payment_method ?? 'cash',
                                                                                                                                            status: row.status ?? 'pending',
                                                                                                                                              };
                                                                                                                                              }

                                                                                                                                              export const financialService = {
                                                                                                                                                async getCommissions(): Promise<CommissionEntry[]> {
                                                                                                                                                    const supabase = createClient();
                                                                                                                                                        if (!supabase) return [];

                                                                                                                                                            try {
                                                                                                                                                                  const { data, error } = await supabase
                                                                                                                                                                          .from('commissions')
                                                                                                                                                                                  .select('*')
                                                                                                                                                                                          .order('created_at', { ascending: false });

                                                                                                                                                                                                if (error) {
                                                                                                                                                                                                        if (isSchemaError(error)) throw error;
                                                                                                                                                                                                                return [];
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                            return (data ?? []).map(toCommission);
                                                                                                                                                                                                                                } catch (e: any) {
                                                                                                                                                                                                                                      if (isSchemaError(e)) throw e;
                                                                                                                                                                                                                                            return [];
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                    async addCommission(entry: Omit<CommissionEntry, 'id' | 'createdAt'>): Promise<boolean> {
                                                                                                                                                                                                                                                        const supabase = createClient();
                                                                                                                                                                                                                                                            if (!supabase) return false;

                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                      const { error } = await supabase.from('commissions').insert({
                                                                                                                                                                                                                                                                              order_id: entry.orderId,
                                                                                                                                                                                                                                                                                      order_date: entry.orderDate,
                                                                                                                                                                                                                                                                                              retailer_name: entry.retailerName,
                                                                                                                                                                                                                                                                                                      order_total: entry.orderTotal,
                                                                                                                                                                                                                                                                                                              commission: entry.commission,
                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                          if (error) {
                                                                                                                                                                                                                                                                                                                                  if (isSchemaError(error)) throw error;
                                                                                                                                                                                                                                                                                                                                          return false;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                      return true;
                                                                                                                                                                                                                                                                                                                                                          } catch (e: any) {
                                                                                                                                                                                                                                                                                                                                                                if (isSchemaError(e)) throw e;
                                                                                                                                                                                                                                                                                                                                                                      return false;
                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                              async getLedgerEntries(): Promise<LedgerEntry[]> {
                                                                                                                                                                                                                                                                                                                                                                                  const supabase = createClient();
                                                                                                                                                                                                                                                                                                                                                                                      if (!supabase) return [];

                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                const { data, error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                        .from('ledger_entries')
                                                                                                                                                                                                                                                                                                                                                                                                                .select('*')
                                                                                                                                                                                                                                                                                                                                                                                                                        .order('created_at', { ascending: false });

                                                                                                                                                                                                                                                                                                                                                                                                                              if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (isSchemaError(error)) throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                              return [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (data ?? []).map(toLedger);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (e: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (isSchemaError(e)) throw e;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  async addLedgerEntry(entry: Omit<LedgerEntry, 'id'>): Promise<boolean> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const supabase = createClient();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!supabase) return false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const { error } = await supabase.from('ledger_entries').insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            entry_date: entry.entryDate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    supplier_id: entry.supplierId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            supplier_name: entry.supplierName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    entry_type: entry.entryType,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            description: entry.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    amount: entry.amount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            direction: entry.direction,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    balance: entry.balance ?? 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            order_id: entry.orderId ?? '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    payment_method: entry.paymentMethod ?? 'cash',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status: entry.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (isSchemaError(error)) throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (e: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (isSchemaError(e)) throw e;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async getTotals(): Promise<{ totalCommission: number; totalSales: number; totalOrders: number }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const supabase = createClient();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!supabase) return { totalCommission: 0, totalSales: 0, totalOrders: 0 };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const { data, error } = await supabase.from('commissions').select('order_total, commission');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (isSchemaError(error)) throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { totalCommission: 0, totalSales: 0, totalOrders: 0 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const rows = data ?? [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              totalCommission: rows.reduce((s: number, r: any) => s + Number(r.commission ?? 0), 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      totalSales: rows.reduce((s: number, r: any) => s + Number(r.order_total ?? 0), 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              totalOrders: rows.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (e: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (isSchemaError(e)) throw e;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { totalCommission: 0, totalSales: 0, totalOrders: 0 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          