-- 002_finance.sql — Finance + Delivery + Relationships
CREATE TABLE public.supplier_orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_number TEXT UNIQUE NOT NULL, status public.supplier_order_status DEFAULT 'pending', payment_status public.payment_status DEFAULT 'pending', customer_name TEXT, total BIGINT DEFAULT 0, supplier_id UUID REFERENCES public.suppliers(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.supplier_order_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), supplier_order_id UUID REFERENCES public.supplier_orders(id) ON DELETE CASCADE, product_id UUID REFERENCES public.products(id) ON DELETE SET NULL, name TEXT NOT NULL, qty INTEGER DEFAULT 1, unit_price BIGINT DEFAULT 0);
CREATE TABLE public.commissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id TEXT NOT NULL, order_date DATE DEFAULT CURRENT_DATE, order_total BIGINT DEFAULT 0, commission BIGINT DEFAULT 0);
CREATE TABLE public.ledger_entries (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), entry_date DATE DEFAULT CURRENT_DATE, supplier_id TEXT, entry_type public.ledger_entry_type DEFAULT 'order', amount BIGINT DEFAULT 0, direction public.ledger_direction DEFAULT 'debit', status public.ledger_status DEFAULT 'pending');
CREATE TABLE public.invoices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), invoice_number TEXT UNIQUE NOT NULL, order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL, retailer_id UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL, supplier_id UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL, total BIGINT DEFAULT 0, currency TEXT DEFAULT 'IQD', payment_status TEXT DEFAULT 'pending', status TEXT DEFAULT 'issued');
CREATE TABLE public.transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), transaction_number TEXT UNIQUE NOT NULL, retailer_id UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL, supplier_id UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL, total_amount BIGINT DEFAULT 0, paid_amount BIGINT DEFAULT 0, payment_status TEXT DEFAULT 'pending', payment_method TEXT DEFAULT 'cod');
CREATE TABLE public.delivery_tasks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE, delivery_profile_id UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL, status TEXT DEFAULT 'pending', delivery_address TEXT, delivery_fee BIGINT DEFAULT 0);
CREATE TABLE public.relationships (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), retailer_id UUID NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE, supplier_id UUID NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE, status TEXT DEFAULT 'pending', credit_limit BIGINT DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(retailer_id, supplier_id));
