-- 004_mvp.sql — MVP features
CREATE TABLE public.addresses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE, label TEXT, governorate TEXT, district TEXT, street TEXT, details TEXT, is_default BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.product_images (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID REFERENCES public.products(id) ON DELETE CASCADE, url TEXT NOT NULL, is_primary BOOLEAN DEFAULT false, sort_order INT DEFAULT 0);
CREATE TABLE public.categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name_ar TEXT NOT NULL, name_en TEXT, parent_id UUID REFERENCES public.categories(id) ON DELETE SET NULL, icon TEXT, is_active BOOLEAN DEFAULT true);
CREATE TABLE public.reviews (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID REFERENCES public.products(id) ON DELETE CASCADE, user_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE, rating INT CHECK (rating BETWEEN 1 AND 5), comment TEXT, is_visible BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.chat_messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sender_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE, receiver_id UUID REFERENCES public.user_profiles(id) ON DELETE CASCADE, message TEXT NOT NULL, is_read BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.coupons (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code TEXT UNIQUE NOT NULL, discount_percent INT DEFAULT 0, max_uses INT DEFAULT 100, used_count INT DEFAULT 0, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.refunds (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL, requested_by UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL, reason TEXT, status TEXT DEFAULT 'pending', amount BIGINT DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE public.cities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name_ar TEXT NOT NULL, name_en TEXT, governorate TEXT, is_active BOOLEAN DEFAULT true);
