// app/supplier-ledger/page.tsx
'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { DollarSign, ArrowRight, Wallet, AlertCircle, CreditCard, TrendingUp } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/lib/supabase/client';

export default function SupplierLedger() {
  const router = useRouter();
    const { signOut } = useAuth();

      const [transactions, setTransactions] = useState<any[]>([]);
        const [loading, setLoading] = useState(false);
          const [error, setError] = useState('');

            useEffect(() => {
                fetchLedgerData();
                  }, []);

                    const fetchLedgerData = async () => {
                        try {
                              setLoading(true);
                                    // جلب الحركات والبيانات المالية أو الطلبات المرتبطة بالحسابات
                                          const { data, error: err } = await supabase.from('orders').select('*');
                                                if (err) throw err;
                                                      if (data) setTransactions(data);
                                                          } catch (err: any) {
                                                                setError('فشل في جلب السجلات المالية والذمم.');
                                                                    } finally {
                                                                          setLoading(false);
                                                                              }
                                                                                };

                                                                                  return (
                                                                                      <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic" dir="rtl">
                                                                                            {/* الشريط العلوي */}
                                                                                                  <header className="bg-slate-900/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
                                                                                                          <div className="flex items-center gap-3">
                                                                                                                    <button
                                                                                                                                onClick={() => router.push('/supplier-central')}
                                                                                                                                            className="h-10 w-10 rounded-xl bg-slate-800 text-slate-300 hover:text-white grid place-items-center transition"
                                                                                                                                                      >
                                                                                                                                                                  <ArrowRight size={20} />
                                                                                                                                                                            </button>
                                                                                                                                                                                      <div>
                                                                                                                                                                                                  <h1 className="text-sm font-black text-white">دفتر الأستاذ والحسابات المالية</h1>
                                                                                                                                                                                                              <p className="text-[11px] text-slate-400">متابعة الأرصدة، الديون، والمدفوعات بالدينار العراقي</p>
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                      </header>

                                                                                                                                                                                                                                            {/* المحتوى الرئيسي */}
                                                                                                                                                                                                                                                  <main className="max-w-6xl mx-auto p-6 space-y-6">
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                  {/* ملخص مالى */}
                                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                    <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                <div className="h-12 w-12 rounded-2xl bg-emerald-500/10 text-emerald-400 grid place-items-center border border-emerald-500/20">
                                                                                                                                                                                                                                                                                                              <Wallet size={22} />
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-slate-400">إجمالي المبيعات المحصلة</p>
                                                                                                                                                                                                                                                                                                                                                                  <p className="text-lg font-black text-white mt-0.5">0 د.ع</p>
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="h-12 w-12 rounded-2xl bg-amber-500/10 text-amber-400 grid place-items-center border border-amber-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                                            <CreditCard size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-slate-400">الذمم والديون المعلقة</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-lg font-black text-white mt-0.5">0 د.ع</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* جدول المعاملات المالية */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-sm font-bold text-white flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <DollarSign size={18} className="text-emerald-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                سجل الحركات المالية والعمليات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-rose-500/10 border border-rose-500/30 text-rose-400 p-3 rounded-xl text-xs flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <AlertCircle size={16} className="shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>{error}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center py-20 text-slate-500 text-xs">جاري تحميل البيانات المالية...</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : transactions.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-center py-20 text-slate-500 text-xs">لا توجد حركات مالية مسجلة حتى الآن.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {transactions.map((tx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={tx.id} className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs font-bold text-white">معاملة مرتبطة بطلب: #{tx.id.slice(0, 8)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-[11px] text-slate-400 mt-0.5">الحالة: {tx.status || 'مكتملة'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs font-bold text-emerald-400">{tx.total_amount || 0} د.ع</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              