'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Settings, ArrowRight, Server, ShieldCheck, Database, RefreshCw, Cpu, CheckCircle2 } from 'lucide-react';

export default function SystemDashboard() {
  const router = useRouter();
    const [syncing, setSyncing] = useState(false);
      const [successMsg, setSuccessMsg] = useState('');

        const handleSystemSync = () => {
            setSyncing(true);
                setSuccessMsg('');
                    setTimeout(() => {
                          setSyncing(false);
                                setSuccessMsg('تمت مزامنة النظام والاتصال بقاعدة البيانات بنجاح تام.');
                                    }, 1500);
                                      };

                                        return (
                                            <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic" dir="rtl">
                                                  {/* الشريط العلوي */}
                                                        <header className="bg-slate-900/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
                                                                <div className="flex items-center gap-3">
                                                                          <button
                                                                                      onClick={() => router.back()}
                                                                                                  className="h-10 w-10 rounded-xl bg-slate-800 text-slate-300 hover:text-white grid place-items-center transition"
                                                                                                            >
                                                                                                                        <ArrowRight size={20} />
                                                                                                                                  </button>
                                                                                                                                            <div>
                                                                                                                                                        <h1 className="text-sm font-black text-white">إدارة النظام والتشغيل</h1>
                                                                                                                                                                    <p className="text-[11px] text-slate-400">حالة الخوادم، الاتصال بقاعدة البيانات، والصيانة العامة</p>
                                                                                                                                                                              </div>
                                                                                                                                                                                      </div>
                                                                                                                                                                                              <button
                                                                                                                                                                                                        onClick={handleSystemSync}
                                                                                                                                                                                                                  disabled={syncing}
                                                                                                                                                                                                                            className="bg-indigo-600 hover:bg-indigo-500 text-white font-bold px-4 py-2.5 rounded-xl text-xs flex items-center gap-2 transition shadow-lg shadow-indigo-600/20 disabled:opacity-50"
                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                              <RefreshCw size={15} className={syncing ? 'animate-spin' : ''} />
                                                                                                                                                                                                                                                        {syncing ? 'جاري المزامنة...' : 'مزامنة النظام'}
                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                      </header>

                                                                                                                                                                                                                                                                            {/* المحتوى الرئيسي */}
                                                                                                                                                                                                                                                                                  <main className="max-w-6xl mx-auto p-6 space-y-6">

                                                                                                                                                                                                                                                                                          {successMsg && (
                                                                                                                                                                                                                                                                                                    <div className="bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 p-4 rounded-2xl text-xs flex items-center gap-2 shadow-lg">
                                                                                                                                                                                                                                                                                                                <CheckCircle2 size={16} className="shrink-0" />
                                                                                                                                                                                                                                                                                                                            <span>{successMsg}</span>
                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                      {/* بطاقات حالة النظام */}
                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                    <div className="h-12 w-12 rounded-2xl bg-emerald-500/10 text-emerald-400 grid place-items-center border border-emerald-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                  <Database size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-slate-400">قاعدة البيانات (Supabase)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm font-bold text-emerald-400 mt-1 flex items-center gap-1.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse"></span> متصل بنجاح
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="h-12 w-12 rounded-2xl bg-indigo-500/10 text-indigo-400 grid place-items-center border border-indigo-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Server size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-slate-400">حالة الخادم (Server)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm font-bold text-white mt-1">Next.js 15 (App Router)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl flex items-center gap-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="h-12 w-12 rounded-2xl bg-blue-500/10 text-blue-400 grid place-items-center border border-blue-500/20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ShieldCheck size={22} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-slate-400">بيئة التشغيل والسوق</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm font-bold text-blue-400 mt-1">السوق العراقي (IQD)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* لوحة التحكم والتحسينات */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 space-y-4 shadow-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-sm font-bold text-white flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Cpu size={18} className="text-indigo-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                أدوات صيانة وتحسين النظام
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="text-xs font-bold text-white">إفراغ الذاكرة المؤقتة (Cache)</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-[11px] text-slate-400">تحديث مؤشرات البيانات والملفات المؤقتة لضمان سرعة الاستجابة.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => alert('تم تنظيف ذاكرة التخزين المؤقت بنجاح.')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="mt-2 bg-slate-900 hover:bg-slate-800 text-slate-200 font-semibold px-3 py-2 rounded-xl text-xs border border-slate-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        تنظيف الكاش الآن
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-slate-950/80 border border-slate-800 p-4 rounded-2xl space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-xs font-bold text-white">فحص سجلات الأخطاء (Logs)</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-[11px] text-slate-400">مراجعة أحدث الاستدعاءات البرمجية والتحقق من سلامة العمليات.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => alert('السجلات نظيفة ولا توجد أخطاء حرجة.')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="mt-2 bg-slate-900 hover:bg-slate-800 text-slate-200 font-semibold px-3 py-2 rounded-xl text-xs border border-slate-700 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      عرض السجلات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
