// app/supplier-settings/page.tsx
'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Settings, ArrowRight, Save, User, Bell, Shield, Store } from 'lucide-react';

export default function SupplierSettings() {
  const router = useRouter();

    const [storeName, setStoreName] = useState('مخازن جملتي المركزية');
      const [phoneNumber, setPhoneNumber] = useState('07700000000');

        return (
            <div className="min-h-screen bg-slate-950 text-slate-100 font-arabic" dir="rtl">
                  {/* الشريط العلوي */}
                        <header className="bg-slate-900/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between sticky top-0 z-50">
                                <div className="flex items-center gap-3">
                                          <button
                                                      onClick={() => router.push('/supplier-central')}
                                                                  className="h-10 w-10 rounded-xl bg-slate-800 text-slate-300 hover:text-white grid place-items-center transition"
                                                                            >
                                                                                        <ArrowRight size={20} />
                                                                                                  </button>
                                                                                                            <div>
                                                                                                                        <h1 className="text-sm font-black text-white">إعدادات ملف التاجر</h1>
                                                                                                                                    <p className="text-[11px] text-slate-400">تحكم في تفاصيل متجرك وتفضيلات النظام</p>
                                                                                                                                              </div>
                                                                                                                                                      </div>
                                                                                                                                                            </header>

                                                                                                                                                                  {/* المحتوى الرئيسي */}
                                                                                                                                                                        <main className="max-w-3xl mx-auto p-6 space-y-6">
                                                                                                                                                                                
                                                                                                                                                                                        {/* نموذج الإعدادات */}
                                                                                                                                                                                                <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-8 shadow-xl space-y-6">
                                                                                                                                                                                                          <div className="flex items-center gap-3 mb-2">
                                                                                                                                                                                                                      <Settings className="text-emerald-400" size={24} />
                                                                                                                                                                                                                                  <h2 className="text-base font-bold text-white">بيانات المتجر الأساسية</h2>
                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                      <div className="space-y-4">
                                                                                                                                                                                                                                                                  <div className="space-y-1.5">
                                                                                                                                                                                                                                                                                <label className="text-xs text-slate-400">اسم المتجر / الشركة</label>
                                                                                                                                                                                                                                                                                              <div className="relative">
                                                                                                                                                                                                                                                                                                              <span className="absolute inset-y-0 right-3.5 flex items-center text-slate-500">
                                                                                                                                                                                                                                                                                                                                <Store size={16} />
                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                                                                                                                                                    value={storeName}
                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setStoreName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full bg-slate-950 border border-slate-800 rounded-2xl px-4 py-3 pr-10 text-xs text-white outline-none focus:border-emerald-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-1.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="text-xs text-slate-400">رقم الهاتف الرسمي</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="absolute inset-y-0 right-3.5 flex items-center text-slate-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <User size={16} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="tel"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={phoneNumber}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setPhoneNumber(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full bg-slate-950 border border-slate-800 rounded-2xl px-4 py-3 pr-10 text-xs text-white outline-none focus:border-emerald-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      dir="ltr"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="w-full bg-emerald-500 hover:bg-emerald-600 text-slate-950 font-bold py-3.5 rounded-2xl text-xs transition flex items-center justify-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Save size={16} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            حفظ التغييرات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* خيارات إضافية */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button className="bg-slate-900/50 border border-slate-800 p-5 rounded-2xl flex items-center gap-4 text-right hover:border-slate-700 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Bell className="text-amber-400" size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-xs font-bold text-white">تفضيلات التنبيهات</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-[10px] text-slate-500">التحكم في إشعارات الطلبات الجديدة</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button className="bg-slate-900/50 border border-slate-800 p-5 rounded-2xl flex items-center gap-4 text-right hover:border-slate-700 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Shield className="text-blue-400" size={20} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs font-bold text-white">الأمان وكلمة المرور</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-[10px] text-slate-500">تحديث بيانات الدخول الخاصة بك</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          