'use client';

import React from 'react';

interface SkeletonProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string;
    variant?: 'text' | 'circular' | 'rectangular';
    }

    /**
     * المكون الأساسي للهيكل الهيكلي
      */
      export function Skeleton({
        className = '',
          variant = 'rectangular',
            ...props
            }: SkeletonProps) {
              const variantClasses =
                  variant === 'circular' ?'rounded-full'
                              : variant === 'text' ?'rounded h-3 my-1' :'rounded-xl';

                                            return (
                                                <div
                                                      className={`animate-pulse bg-muted/70 ${variantClasses} ${className}`.trim()}
                                                            {...props}
                                                                />
                                                                  );
                                                                  }

                                                                  /**
                                                                   * هيكل التحميل للوحة التحكم والبيانات الإحصائية
                                                                    */
                                                                    export function DashboardSkeleton() {
                                                                      return (
                                                                          <div className="space-y-6 animate-in fade-in duration-300" dir="rtl">
                                                                                {/* KPI grid skeleton */}
                                                                                      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-3 sm:gap-4">
                                                                                              {Array.from({ length: 4 }).map((_, i) => (
                                                                                                        <div
                                                                                                                    key={`kpi-skel-${i + 1}`}
                                                                                                                                className="bg-card border border-border/60 rounded-2xl p-4 space-y-3 shadow-xs"
                                                                                                                                          >
                                                                                                                                                      <div className="flex justify-between items-center">
                                                                                                                                                                    <Skeleton className="h-3.5 w-24" />
                                                                                                                                                                                  <Skeleton className="h-9 w-9" variant="circular" />
                                                                                                                                                                                              </div>
                                                                                                                                                                                                          <Skeleton className="h-7 w-28" />
                                                                                                                                                                                                                      <Skeleton className="h-3 w-16" />
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                    {/* Charts skeleton */}
                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                  <div className="xl:col-span-2 bg-card border border-border/60 rounded-2xl p-4 space-y-4 shadow-xs">
                                                                                                                                                                                                                                                                            <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                        <Skeleton className="h-4 w-36" />
                                                                                                                                                                                                                                                                                                    <Skeleton className="h-8 w-24" />
                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                        <Skeleton className="h-56 w-full" />
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                        <div className="bg-card border border-border/60 rounded-2xl p-4 space-y-4 shadow-xs">
                                                                                                                                                                                                                                                                                                                                                  <Skeleton className="h-4 w-28" />
                                                                                                                                                                                                                                                                                                                                                            <Skeleton className="h-56 w-full" />
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                {/* Table skeleton */}
                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-card border border-border/60 rounded-2xl p-4 space-y-3 shadow-xs">
                                                                                                                                                                                                                                                                                                                                                                                              <Skeleton className="h-4 w-40 mb-2" />
                                                                                                                                                                                                                                                                                                                                                                                                      {Array.from({ length: 5 }).map((_, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                <Skeleton key={`trow-skel-${i + 1}`} className="h-12 w-full" />
                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                                                                                     * هيكل التحميل للجداول
                                                                                                                                                                                                                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                                                                                                                                                                                                                      export function TableSkeleton({
                                                                                                                                                                                                                                                                                                                                                                                                                                        rows = 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                          cols = 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                          }: {
                                                                                                                                                                                                                                                                                                                                                                                                                                            rows?: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                              cols?: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                              }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="w-full space-y-2 border border-border/60 rounded-2xl p-3 bg-card" dir="rtl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Table Header */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-4 p-3 bg-muted/40 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {Array.from({ length: cols }).map((_, c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Skeleton key={`tskel-th-${c + 1}`} className="h-4 flex-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Table Rows */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {Array.from({ length: rows }).map((_, r) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={`tskel-row-${r + 1}`} className="flex gap-4 p-3 border-b border-border/30 last:border-none">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {Array.from({ length: cols }).map((_, c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Skeleton key={`tskel-cell-${r + 1}-${c + 1}`} className="h-4 flex-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * هيكل التحميل لشريحة المنتجات أو البطاقات المربعة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export function ProductGridSkeleton({ count = 6 }: { count?: number }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3 sm:gap-4" dir="rtl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {Array.from({ length: count }).map((_, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={`prod-skel-${i + 1}`} className="bg-card border border-border/60 rounded-2xl p-3 space-y-3 shadow-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Skeleton className="h-32 sm:h-40 w-full rounded-xl" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Skeleton className="h-4 w-3/4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Skeleton className="h-3 w-1/2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between items-center pt-2 border-t border-border/40">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Skeleton className="h-5 w-16" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Skeleton className="h-8 w-8" variant="circular" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default Skeleton;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            