'use client';

import React, { memo, useMemo } from 'react';
import { TrendingUp, TrendingDown, Minus } from 'lucide-react';

export interface MetricCardProps {
  label: string;
    value: string | number;
      subValue?: string;
        trend?: 'up' | 'down' | 'neutral';
          trendValue?: string;
            icon: React.ReactNode;
              variant?: 'default' | 'success' | 'warning' | 'danger' | 'primary';
                size?: 'default' | 'hero';
                  className?: string;
                    onClick?: () => void;
                    }

                    const variantStyles: Record<NonNullable<MetricCardProps['variant']>, string> = {
                      default:
                          'bg-card border-border/70 text-card-foreground hover:border-border',
                            success:
                                'bg-emerald-500/10 border-emerald-500/20 text-emerald-950 dark:text-emerald-100',
                                  warning:
                                      'bg-amber-500/10 border-amber-500/20 text-amber-950 dark:text-amber-100',
                                        danger:
                                            'bg-rose-500/10 border-rose-500/20 text-rose-950 dark:text-rose-100',
                                              primary:
                                                  'bg-primary border-primary/30 text-primary-foreground shadow-sm',
                                                  };

                                                  const trendIconMap = {
                                                    up: TrendingUp,
                                                      down: TrendingDown,
                                                        neutral: Minus,
                                                        };

                                                        export const MetricCard = memo(function MetricCard({
                                                          label,
                                                            value,
                                                              subValue,
                                                                trend,
                                                                  trendValue,
                                                                    icon,
                                                                      variant = 'default',
                                                                        size = 'default',
                                                                          className = '',
                                                                            onClick,
                                                                            }: MetricCardProps) {
                                                                              const isPrimary = variant === 'primary';
                                                                                const TrendIcon = trend ? trendIconMap[trend] : null;

                                                                                  // تحديد ألوان الاتجاه حسب نوع الكارت
                                                                                    const trendColor = useMemo(() => {
                                                                                        if (!trend) return '';
                                                                                            if (isPrimary) return 'text-primary-foreground/90';

                                                                                                switch (trend) {
                                                                                                      case 'up':
                                                                                                              return 'text-emerald-600 dark:text-emerald-400';
                                                                                                                    case 'down':
                                                                                                                            return 'text-rose-600 dark:text-rose-400';
                                                                                                                                  case 'neutral':
                                                                                                                                        default:
                                                                                                                                                return 'text-muted-foreground';
                                                                                                                                                    }
                                                                                                                                                      }, [trend, isPrimary]);

                                                                                                                                                        const containerClasses = useMemo(() => {
                                                                                                                                                            const base = [
                                                                                                                                                                  'relative rounded-2xl border transition-all duration-200 select-none overflow-hidden',
                                                                                                                                                                        variantStyles[variant],
                                                                                                                                                                              size === 'hero' ? 'p-5 sm:p-6' : 'p-4',
                                                                                                                                                                                  ];

                                                                                                                                                                                      if (onClick) {
                                                                                                                                                                                            base.push(
                                                                                                                                                                                                    'cursor-pointer hover:shadow-md active:scale-[0.98] hover:border-primary/40'
                                                                                                                                                                                                          );
                                                                                                                                                                                                              }

                                                                                                                                                                                                                  if (className) base.push(className);

                                                                                                                                                                                                                      return base.join(' ');
                                                                                                                                                                                                                        }, [variant, size, onClick, className]);

                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                    className={containerClasses}
                                                                                                                                                                                                                                          onClick={onClick}
                                                                                                                                                                                                                                                role={onClick ? 'button' : undefined}
                                                                                                                                                                                                                                                      tabIndex={onClick ? 0 : undefined}
                                                                                                                                                                                                                                                            onKeyDown={
                                                                                                                                                                                                                                                                    onClick
                                                                                                                                                                                                                                                                              ? (e) => {
                                                                                                                                                                                                                                                                                            if (e.key === 'Enter' || e.key === ' ') {
                                                                                                                                                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                                                                                                                                                            onClick();
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                : undefined
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                {/* Header Row: Label & Icon */}
                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center justify-between gap-2 mb-2.5">
                                                                                                                                                                                                                                                                                                                                                                                              <p
                                                                                                                                                                                                                                                                                                                                                                                                        className={`text-xs font-bold tracking-wide font-arabic truncate ${
                                                                                                                                                                                                                                                                                                                                                                                                                    isPrimary ? 'text-primary-foreground/80' : 'text-muted-foreground'
                                                                                                                                                                                                                                                                                                                                                                                                                              }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                {label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`rounded-xl p-2 flex-shrink-0 flex items-center justify-center ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      isPrimary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? 'bg-white/15 text-primary-foreground'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : 'bg-muted/60 text-foreground border border-border/40'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {icon}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Main Metric Value */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-0.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`tabular-nums font-extrabold leading-tight ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size === 'hero' ? 'text-2xl sm:text-3xl' : 'text-xl sm:text-2xl'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } ${isPrimary ? 'text-primary-foreground' : 'text-foreground'}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {value}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {subValue && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className={`text-xs font-medium truncate ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      isPrimary ? 'text-primary-foreground/70' : 'text-muted-foreground'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {subValue}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Trend Row */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {trend && trendValue && TrendIcon && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className={`flex items-center gap-1.5 mt-3 pt-2 border-t border-border/20 ${trendColor}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <TrendIcon size={14} className="flex-shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-xs font-bold tabular-nums dir-ltr text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {trendValue}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  MetricCard.displayName = 'MetricCard';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default MetricCard;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  