'use client';

import React, { memo } from 'react';

export type OrderStatus = 'جديد' | 'مقبول' | 'قيد التجهيز' | 'خرج للتوصيل' | 'مُسلَّم' | 'ملغي' | 'pending' | 'accepted' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
export type StockStatus = 'متوفر' | 'منخفض' | 'نفد' | 'موقوف' | 'in_stock' | 'low_stock' | 'out_of_stock';
export type PaymentStatus = 'مدفوع' | 'آجل' | 'جزئي' | 'متأخر' | 'paid' | 'deferred' | 'partial' | 'overdue';

export type BadgeStatus = OrderStatus | StockStatus | PaymentStatus | string;

interface StatusConfig {
  label: string;
    className: string;
      dotClass: string;
      }

      const statusMap: Record<string, StatusConfig> = {
        // حالات الطلبات
          'جديد': {
              label: 'جديد',
                  className: 'bg-sky-500/15 text-sky-700 dark:text-sky-300 border-sky-500/30',
                      dotClass: 'bg-sky-500',
                        },
                          'pending': {
                              label: 'جديد',
                                  className: 'bg-sky-500/15 text-sky-700 dark:text-sky-300 border-sky-500/30',
                                      dotClass: 'bg-sky-500',
                                        },
                                          'مقبول': {
                                              label: 'مقبول',
                                                  className: 'bg-indigo-500/15 text-indigo-700 dark:text-indigo-300 border-indigo-500/30',
                                                      dotClass: 'bg-indigo-500',
                                                        },
                                                          'accepted': {
                                                              label: 'مقبول',
                                                                  className: 'bg-indigo-500/15 text-indigo-700 dark:text-indigo-300 border-indigo-500/30',
                                                                      dotClass: 'bg-indigo-500',
                                                                        },
                                                                          'قيد التجهيز': {
                                                                              label: 'قيد التجهيز',
                                                                                  className: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30',
                                                                                      dotClass: 'bg-amber-500',
                                                                                        },
                                                                                          'processing': {
                                                                                              label: 'قيد التجهيز',
                                                                                                  className: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30',
                                                                                                      dotClass: 'bg-amber-500',
                                                                                                        },
                                                                                                          'خرج للتوصيل': {
                                                                                                              label: 'خرج للتوصيل',
                                                                                                                  className: 'bg-purple-500/15 text-purple-700 dark:text-purple-300 border-purple-500/30',
                                                                                                                      dotClass: 'bg-purple-500',
                                                                                                                        },
                                                                                                                          'shipped': {
                                                                                                                              label: 'خرج للتوصيل',
                                                                                                                                  className: 'bg-purple-500/15 text-purple-700 dark:text-purple-300 border-purple-500/30',
                                                                                                                                      dotClass: 'bg-purple-500',
                                                                                                                                        },
                                                                                                                                          'مُسلَّم': {
                                                                                                                                              label: 'مُسلَّم',
                                                                                                                                                  className: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
                                                                                                                                                      dotClass: 'bg-emerald-500',
                                                                                                                                                        },
                                                                                                                                                          'delivered': {
                                                                                                                                                              label: 'مُسلَّم',
                                                                                                                                                                  className: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
                                                                                                                                                                      dotClass: 'bg-emerald-500',
                                                                                                                                                                        },
                                                                                                                                                                          'ملغي': {
                                                                                                                                                                              label: 'ملغي',
                                                                                                                                                                                  className: 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
                                                                                                                                                                                      dotClass: 'bg-rose-500',
                                                                                                                                                                                        },
                                                                                                                                                                                          'cancelled': {
                                                                                                                                                                                              label: 'ملغي',
                                                                                                                                                                                                  className: 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
                                                                                                                                                                                                      dotClass: 'bg-rose-500',
                                                                                                                                                                                                        },

                                                                                                                                                                                                          // حالات المخزون
                                                                                                                                                                                                            'متوفر': {
                                                                                                                                                                                                                label: 'متوفر',
                                                                                                                                                                                                                    className: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
                                                                                                                                                                                                                        dotClass: 'bg-emerald-500',
                                                                                                                                                                                                                          },
                                                                                                                                                                                                                            'in_stock': {
                                                                                                                                                                                                                                label: 'متوفر',
                                                                                                                                                                                                                                    className: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
                                                                                                                                                                                                                                        dotClass: 'bg-emerald-500',
                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                            'منخفض': {
                                                                                                                                                                                                                                                label: 'منخفض',
                                                                                                                                                                                                                                                    className: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30',
                                                                                                                                                                                                                                                        dotClass: 'bg-amber-500',
                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                            'low_stock': {
                                                                                                                                                                                                                                                                label: 'منخفض',
                                                                                                                                                                                                                                                                    className: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30',
                                                                                                                                                                                                                                                                        dotClass: 'bg-amber-500',
                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                            'نفد': {
                                                                                                                                                                                                                                                                                label: 'نفد',
                                                                                                                                                                                                                                                                                    className: 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
                                                                                                                                                                                                                                                                                        dotClass: 'bg-rose-500',
                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                            'out_of_stock': {
                                                                                                                                                                                                                                                                                                label: 'نفد',
                                                                                                                                                                                                                                                                                                    className: 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
                                                                                                                                                                                                                                                                                                        dotClass: 'bg-rose-500',
                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                            'موقوف': {
                                                                                                                                                                                                                                                                                                                label: 'موقوف',
                                                                                                                                                                                                                                                                                                                    className: 'bg-slate-500/15 text-slate-700 dark:text-slate-300 border-slate-500/30',
                                                                                                                                                                                                                                                                                                                        dotClass: 'bg-slate-500',
                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                            // حالات الدفع
                                                                                                                                                                                                                                                                                                                              'مدفوع': {
                                                                                                                                                                                                                                                                                                                                  label: 'مدفوع',
                                                                                                                                                                                                                                                                                                                                      className: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
                                                                                                                                                                                                                                                                                                                                          dotClass: 'bg-emerald-500',
                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                              'paid': {
                                                                                                                                                                                                                                                                                                                                                  label: 'مدفوع',
                                                                                                                                                                                                                                                                                                                                                      className: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
                                                                                                                                                                                                                                                                                                                                                          dotClass: 'bg-emerald-500',
                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                              'آجل': {
                                                                                                                                                                                                                                                                                                                                                                  label: 'آجل',
                                                                                                                                                                                                                                                                                                                                                                      className: 'bg-sky-500/15 text-sky-700 dark:text-sky-300 border-sky-500/30',
                                                                                                                                                                                                                                                                                                                                                                          dotClass: 'bg-sky-500',
                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                              'deferred': {
                                                                                                                                                                                                                                                                                                                                                                                  label: 'آجل',
                                                                                                                                                                                                                                                                                                                                                                                      className: 'bg-sky-500/15 text-sky-700 dark:text-sky-300 border-sky-500/30',
                                                                                                                                                                                                                                                                                                                                                                                          dotClass: 'bg-sky-500',
                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                              'جزئي': {
                                                                                                                                                                                                                                                                                                                                                                                                  label: 'جزئي',
                                                                                                                                                                                                                                                                                                                                                                                                      className: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30',
                                                                                                                                                                                                                                                                                                                                                                                                          dotClass: 'bg-amber-500',
                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                              'partial': {
                                                                                                                                                                                                                                                                                                                                                                                                                  label: 'جزئي',
                                                                                                                                                                                                                                                                                                                                                                                                                      className: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30',
                                                                                                                                                                                                                                                                                                                                                                                                                          dotClass: 'bg-amber-500',
                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                              'متأخر': {
                                                                                                                                                                                                                                                                                                                                                                                                                                  label: 'متأخر',
                                                                                                                                                                                                                                                                                                                                                                                                                                      className: 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
                                                                                                                                                                                                                                                                                                                                                                                                                                          dotClass: 'bg-rose-500',
                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                              'overdue': {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  label: 'متأخر',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      className: 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          dotClass: 'bg-rose-500',
                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                            const defaultConfig: StatusConfig = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              label: '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                className: 'bg-slate-500/15 text-slate-700 dark:text-slate-300 border-slate-500/30',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dotClass: 'bg-slate-500',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export interface StatusBadgeProps {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status: BadgeStatus;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size?: 'sm' | 'md';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        showDot?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            customLabel?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export const StatusBadge = memo(function StatusBadge({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                size = 'md',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  showDot = true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className = '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      customLabel,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }: StatusBadgeProps) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const config = statusMap[status] || {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...defaultConfig,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                label: status || 'غير محدد',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const displayLabel = customLabel || config.label;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const sizeClasses =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          size === 'sm' ?'text-[11px] px-2 py-0.5 gap-1 font-medium' :'text-xs px-2.5 py-1 gap-1.5 font-semibold';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          inline-flex items-center justify-center border rounded-full font-arabic whitespace-nowrap transition-colors select-none
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ${sizeClasses}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ${config.className}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ${className}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `.trim()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {showDot && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${config.dotClass}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              aria-hidden="true"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>{displayLabel}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        StatusBadge.displayName = 'StatusBadge';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default StatusBadge;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        