'use client';

import React, { createContext, useContext, useState, useCallback, useEffect, useMemo } from 'react';
import { CheckCircle2, AlertCircle, Info, X, ShoppingCart, Package } from 'lucide-react';

export type ToastType = 'success' | 'error' | 'info' | 'cart' | 'order';

export interface Toast {
  id: string;
    type: ToastType;
      message: string;
        subMessage?: string;
          duration?: number;
          }

          export interface ToastHelpers {
            success: (message: string, subMessage?: string, duration?: number) => void;
              error: (message: string, subMessage?: string, duration?: number) => void;
                info: (message: string, subMessage?: string, duration?: number) => void;
                  cart: (message: string, subMessage?: string, duration?: number) => void;
                    order: (message: string, subMessage?: string, duration?: number) => void;
                    }

                    export interface ToastContextValue {
                      showToast: (type: ToastType, message: string, subMessage?: string, duration?: number) => void;
                        toast: ToastHelpers;
                        }

                        const ToastContext = createContext<ToastContextValue | undefined>(undefined);

                        export function useToast() {
                          const context = useContext(ToastContext);
                            if (!context) {
                                throw new Error('useToast must be used within a ToastProvider');
                                  }
                                    return context;
                                    }

                                    const toastConfig: Record<
                                      ToastType,
                                        {
                                            icon: React.ElementType;
                                                iconBg: string;
                                                    borderClass: string;
                                                        iconColor: string;
                                                          }
                                                          > = {
                                                            success: {
                                                                icon: CheckCircle2,
                                                                    iconBg: 'bg-emerald-500/15',
                                                                        borderClass: 'border-emerald-500/30',
                                                                            iconColor: 'text-emerald-600 dark:text-emerald-400',
                                                                              },
                                                                                error: {
                                                                                    icon: AlertCircle,
                                                                                        iconBg: 'bg-rose-500/15',
                                                                                            borderClass: 'border-rose-500/30',
                                                                                                iconColor: 'text-rose-600 dark:text-rose-400',
                                                                                                  },
                                                                                                    info: {
                                                                                                        icon: Info,
                                                                                                            iconBg: 'bg-sky-500/15',
                                                                                                                borderClass: 'border-sky-500/30',
                                                                                                                    iconColor: 'text-sky-600 dark:text-sky-400',
                                                                                                                      },
                                                                                                                        cart: {
                                                                                                                            icon: ShoppingCart,
                                                                                                                                iconBg: 'bg-primary/15',
                                                                                                                                    borderClass: 'border-primary/30',
                                                                                                                                        iconColor: 'text-primary',
                                                                                                                                          },
                                                                                                                                            order: {
                                                                                                                                                icon: Package,
                                                                                                                                                    iconBg: 'bg-purple-500/15',
                                                                                                                                                        borderClass: 'border-purple-500/30',
                                                                                                                                                            iconColor: 'text-purple-600 dark:text-purple-400',
                                                                                                                                                              },
                                                                                                                                                              };

                                                                                                                                                              function ToastItem({ toast, onRemove }: { toast: Toast; onRemove: (id: string) => void }) {
                                                                                                                                                                const [visible, setVisible] = useState(false);
                                                                                                                                                                  const cfg = toastConfig[toast.type];
                                                                                                                                                                    const IconComponent = cfg.icon;

                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                          // أنيميشن الدخول
                                                                                                                                                                              const t1 = setTimeout(() => setVisible(true), 10);

                                                                                                                                                                                  // الاختفاء التلقائي
                                                                                                                                                                                      const t2 = setTimeout(() => {
                                                                                                                                                                                            setVisible(false);
                                                                                                                                                                                                  setTimeout(() => onRemove(toast.id), 300);
                                                                                                                                                                                                      }, toast.duration ?? 3500);

                                                                                                                                                                                                          return () => {
                                                                                                                                                                                                                clearTimeout(t1);
                                                                                                                                                                                                                      clearTimeout(t2);
                                                                                                                                                                                                                          };
                                                                                                                                                                                                                            }, [toast.id, toast.duration, onRemove]);

                                                                                                                                                                                                                              const handleManualDismiss = () => {
                                                                                                                                                                                                                                  setVisible(false);
                                                                                                                                                                                                                                      setTimeout(() => onRemove(toast.id), 300);
                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                    role="status"
                                                                                                                                                                                                                                                          aria-live="polite"
                                                                                                                                                                                                                                                                dir="rtl"
                                                                                                                                                                                                                                                                      className={`flex items-start gap-3 px-4 py-3 rounded-2xl border shadow-lg backdrop-blur-md bg-card/95 text-card-foreground w-full transition-all duration-300 font-arabic ${cfg.borderClass} ${
                                                                                                                                                                                                                                                                              visible ? 'opacity-100 translate-y-0 scale-100' : 'opacity-0 translate-y-4 scale-95'
                                                                                                                                                                                                                                                                                    }`}
                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                              <div className={`w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 ${cfg.iconBg}`}>
                                                                                                                                                                                                                                                                                                      <IconComponent size={18} className={cfg.iconColor} />
                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                  <div className="flex-1 min-w-0 pt-0.5">
                                                                                                                                                                                                                                                                                                                          <p className="text-sm font-bold leading-snug text-foreground truncate">{toast.message}</p>
                                                                                                                                                                                                                                                                                                                                  {toast.subMessage && (
                                                                                                                                                                                                                                                                                                                                            <p className="text-xs text-muted-foreground mt-0.5 leading-relaxed">{toast.subMessage}</p>
                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                        onClick={handleManualDismiss}
                                                                                                                                                                                                                                                                                                                                                                                type="button"
                                                                                                                                                                                                                                                                                                                                                                                        className="p-1 text-muted-foreground hover:text-foreground hover:bg-muted/50 rounded-lg transition-colors flex-shrink-0 -me-1"
                                                                                                                                                                                                                                                                                                                                                                                                aria-label="إغلاق التنبيه"
                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                              <X size={16} />
                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                          export function ToastProvider({ children }: { children: React.ReactNode }) {
                                                                                                                                                                                                                                                                                                                                                                                                                            const [toasts, setToasts] = useState<Toast[]>([]);

                                                                                                                                                                                                                                                                                                                                                                                                                              const showToast = useCallback((type: ToastType, message: string, subMessage?: string, duration?: number) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                  const id = `toast-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                      setToasts((prev) => [...prev.slice(-2), { id, type, message, subMessage, duration }]);
                                                                                                                                                                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                          const removeToast = useCallback((id: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                              setToasts((prev) => prev.filter((t) => t.id !== id));
                                                                                                                                                                                                                                                                                                                                                                                                                                                }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                  const toastHelpers: ToastHelpers = useMemo(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      () => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                            success: (msg, subMsg, dur) => showToast('success', msg, subMsg, dur),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  error: (msg, subMsg, dur) => showToast('error', msg, subMsg, dur),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        info: (msg, subMsg, dur) => showToast('info', msg, subMsg, dur),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cart: (msg, subMsg, dur) => showToast('cart', msg, subMsg, dur),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    order: (msg, subMsg, dur) => showToast('order', msg, subMsg, dur),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [showToast]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ToastContext.Provider value={{ showToast, toast: toastHelpers }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {children}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Container - تم تعديل المسافة من الأسفل للتوافق مع BottomNav */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="fixed bottom-20 md:bottom-8 left-1/2 -translate-x-1/2 z-[100] flex flex-col gap-2 items-center pointer-events-none w-full max-w-sm px-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {toasts.map((toastItem) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={toastItem.id} className="pointer-events-auto w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ToastItem toast={toastItem} onRemove={removeToast} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ToastContext.Provider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  